### ISSUE TITLE
Error on opening DB objects properties

### ISSUE THREAD

**Issue by blumf** [mariuz/flamerobin#10]
#On earlier builds I was seeing FR lock-up when trying to open up the Properties dialog for tables/views/etc. Used to happen occasionally, but recently has been consistent.

Trying the new 0.9.3 x64 build there's an improvement in that an error message is displayed:

![flamerobin_error](https://cloud.githubusercontent.com/assets/130734/22372823/c51eec3a-e496-11e6-8cb9-cb6afec9bebe.png)

And I can skip the error with 'Cancel', everything seems okay at that point.

Win7 64bit if that help

**Comment by mariuz** [comment]
It's a known issue , I will do a rebuild with wx 3.0 and previous VS

**Comment by tomcon** [comment]
Six months on, any update on this please, seems related to other recent issues.

**Comment by blumf** [comment]
Yep, things have gotten worse now. I'm seeing an error about 'Access violation - No RTTI data' which is stopping me seeing any DB object's properties other than the summary.

**Comment by arvanus** [comment]
Hi, please test the latest snapshot available and let me know if it's working
https://github.com/mariuz/flamerobin/releases/tag/0.9.3.2

**Comment by blumf** [comment]
Don't suppose you have a plain zip of the build, so I can just try it without messing around with pre-existing install.

**Comment by arvanus** [comment]
@blumf 
Done, uploaded a .zip, if this topic is completed, please let me know or close this issue.
Thanks

**Comment by blumf** [comment]
That seems to be working well, thanks. And a better CSV export too, excellent!
