### ISSUE TITLE
Double lock in Database::connect

### ISSUE THREAD

**Issue by blumf** [mariuz/flamerobin#106]
In my tidying up I spotted a double use of a SubjectLocker in the Database::connect method [here](https://github.com/mariuz/flamerobin/blob/master/src/metadata/database.cpp#L1005) and [here](https://github.com/mariuz/flamerobin/blob/master/src/metadata/database.cpp#L1091).

Not 100% sure on the way SubjectLocker works, but I think that outer scope lock is all that's needed here. However, that may be overreach, and just the inner scope is required.

**Comment by arvanus** [comment]
Could this be related with #65?

**Comment by blumf** [comment]
Possibly, can't say I've run into the issue so I can't check.

Looking at the SubjectLocker and Subject classes, it doesn't seem like the Subject class does anything in a specifically thread safe way, no mutexes or atomics. But it's not clear that it has to.

I removed the inner lock, and connecting to DBs still works, so... maybe that's okay?

**Comment by arvanus** [comment]
You simply removed the second lock?
https://github.com/mariuz/flamerobin/blob/0d272726e000d716b1270cddae66231019b8c70b/src/metadata/database.cpp#L1091
I'll run some tests here too, can you confirm it?
Thanks

**Comment by blumf** [comment]
Yeah the line 1091 one.

As far as I can make out, it just stops some events being sent until after the locks are destructed. One or the other should do, and it looks like the wider scope of the first lock would be fine.

It's not a multi-threading thing, that's just in one part of the function and doesn't seem to have any relation to these SubjectLocker items.

(for another ticket: that's the only place Boost is used, and now we're onto C++14 we can probably replace that with std::thread or similar and ditch the Boost requirement)

**Comment by arvanus** [comment]
The least dependencies, the better :)
Taking a look here, there isn't a lot of places referencing boost, but I sincerely don't work daily and I'm not an expert at threading in C++ here :), if you believe this changes will be as painless as possible, I'm glad to help

**Comment by arvanus** [comment]
@Jdochoa is working hard too to enable more Fb3 compatibility so maybe there will be some small gaps here 👍

**Comment by arvanus** [comment]
Just tested, not related to #65 😢

**Comment by luronumen** [comment]
> Just tested, not related to #65 😢
😢

**Comment by luronumen** [comment]
Hi @blumf ,
 
Is this issue still reproducible in [0.9.3.8 Snapshot](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.8) version?

**Comment by blumf** [comment]
Not noticing anything, although it was mainly a code issue than runtime.

Snapshot's great BTW :)

**Comment by luronumen** [comment]
Hi @blumf 

thanks for you reply! Could you please close this issue in case of the code issue is fixed?

Best Regards,
Luciano
