### ISSUE TITLE
in last windows exe gives error when trying to open table

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [mariuz/flamerobin#11]
![image 1](https://cloud.githubusercontent.com/assets/3578953/22835456/f1ba2700-ef9f-11e6-9811-7e3592ee49c9.png)

Windows 10 Java 8

**Comment by tomcon** [comment]
Lastest version of Flamerobin doesn't run on Windows server 2012 either

**Comment by arvanus** [comment]
Hi, please test the latest snapshot available and let me know if it's working 
https://github.com/mariuz/flamerobin/releases/tag/0.9.3.2

**Comment by erickdeoliveiraleal** [comment]
yes, it's fine
