### ISSUE TITLE
wxWidget 3.1.4 compatibility

### ISSUE THREAD

**Issue by arvanus** [mariuz/flamerobin#119]
Almost everything looks to work fine, but Privileges tab is buggy, the hint work like a Win98 computer 😄 
![image](https://user-images.githubusercontent.com/8182958/94343425-81035500-ffee-11ea-9327-334cc71cd810.png)

in the HTML, looks like  `<a href="info://Granted by SYSDBA">` works fine until wxHtmlWindow 3.1.3. At 3.1.4 wx team switched to an Edge implementation in Windows:
https://www.wxwidgets.org/news/2020/07/wxwidgets-3.1.4-released/
```
 <tbody>
    <tr bgcolor="navy">
      <td><b><font color="white">Grantee</font></b></td>
      <td><b><font color="white">Select</font></b></td>
      <td><b><font color="white">Insert</font></b></td>
      <td><b><font color="white">Update</font></b></td>
      <td><b><font color="white">Delete</font></b></td>
      <td><b><font color="white">Reference</font></b></td>
    </tr>
    
    <tr bgcolor="#DDDDFF">
      <td nowrap valign="top">SYSDBA</td>
      <td valign="top" align="center"><a href="info://Granted by SYSDBA">
          <img src="html-templates\ok2.png"></a><font size="-1"></font>
          
      </td>
      <td valign="top" align="center"><a href="info://Granted by SYSDBA">
          <img src="html-templates\ok2.png"></a><font size="-1"></font>
          
      </td>
      <td valign="top" align="center"><a href="info://Granted by SYSDBA">
          <img src="html-templates\ok2.png"></a><font size="-1"></font>
          
      </td>
      <td valign="top" align="center"><a href="info://Granted by SYSDBA">
          <img src="html-templates\ok2.png"></a><font size="-1"></font>
          
      </td>
      <td valign="top" align="center"><a href="info://Granted by SYSDBA">
          <img src="html-templates\ok2.png"></a><font size="-1"></font>
          
      </td>
    </tr>
  </tbody>
</table>
```

**Comment by luronumen** [comment]
Interesting bug. Let's see how we can fix this.

**Comment by arvanus** [comment]
Looks like something here:
https://github.com/mariuz/flamerobin/blob/7e926d5a5271e1650a30209defc31163e2e30888/src/gui/MetadataItemPropertiesFrame.cpp#L337-L351
At previous version, you wasn't required to release the previous `wxTipWindow` or something like this
I Will work on this :)

**Comment by luronumen** [comment]
Excellent @arvanus !

**Comment by luronumen** [comment]
Hi @arvanus,
 
Is this issue still reproducible in [0.9.3.8 Snapshot](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.8) version?

**Comment by arvanus** [comment]
No, thanks
