### ISSUE TITLE
 not working on macOS Catalina

### ISSUE THREAD

**Issue by criscubillosedi** [mariuz/flamerobin#126]
hi, i can't start the application from my macOS Catalina (version 0.9.2).

I have tried to run it from Terminal and had the following result:

 /Applications/FlameRobin.app/Contents/MacOS/flamerobin 
zsh: bad CPU type in executable: /Applications/FlameRobin.app/Contents/MacOS/flamerobin

**Comment by arvanus** [comment]
Sorry, I can't hep with macOS, can you trie to build from the source in the latest snapshot please?

**Comment by criscubillosedi** [comment]
Effectively, I manually compiled the sources and I was able to generate a working version. However, not everyone knows how to do this and it seems that the application simply no longer works with recent versions of MacOS.
I recommend generating a new package (Flamerobin.app) for Mac.
I really do not know if the package generated on my Mac will serve everyone.
