### ISSUE TITLE
Portable

### ISSUE THREAD

**Issue by regs01** [mariuz/flamerobin#127]
Is it possible to make optional location for configuration stored in program folder. Something like named **conf** folder. So to use it if it exist.

**Comment by arvanus** [comment]
You already can do it without problems!
Steps:
Prepare your FR folder coping everything from the installation folder:

- code-templates
- conf-defs
- docs
- html-templates
- sys-templates
- flamerobin.exe
- fbclient.dll

Then, create a new folder, lets call "user"
Finally, create a .bat with this content (for Windows)

`./Flamerobin.exe /uh .\user /h .\`

Save, run and get fun 👍

**Comment by wanderleihuttel** [comment]
I've tried the option above and did't work. 

Would be possible include an option in Flamerobin to inform the path of fblient.dll?

**Comment by arvanus** [comment]
already available under View->Preferences->General
