### ISSUE TITLE
wrong binaries (git hash) in tag 0.9.3.4

### ISSUE THREAD

**Issue by trynn** [mariuz/flamerobin#137]
relating to `flamerobin-0.9.3.2c166a5b.zip`

the attached binaries to tag `0.9.3.4` does show the git hash `2167da96` on my system.
![image](https://user-images.githubusercontent.com/4052289/98739300-607a3900-23a9-11eb-9fda-1d6f22df5e62.png)

This does not match the github hash.
The tags before (`0.9.3.3`, `0.9.3.2`) does reflect the github hash. it may be just an error in release workflow.
In general, i would appreciate better binary identification for upcoming releases.
 - windows/properties/details/version
 - flamerobin.exe/help/about

the package has the updated documentations in `docs/fr_whatsnew.html` tho.

**Comment by arvanus** [comment]
Sorry, my bad
This refers to 2167da952aa745e73af3ed8ddbf4acbd28bcabf5 commit, probably I forgot to run update-revision-info.cmd 
In the new cmake build process looks like it will run automatically

**Comment by trynn** [comment]
no problem. just wanted to raise attention here.

**Comment by arvanus** [comment]
Closing as a new snapshot is released
