### ISSUE TITLE
Long freeze at connecting to database

### ISSUE THREAD

**Issue by arvanus** [mariuz/flamerobin#138]
With new Fb3 merge 82c4fac, the connection freeze at this screen when connecting to an remote DB:
![image](https://user-images.githubusercontent.com/8182958/98886583-22e1e280-2473-11eb-9d6a-cc40c5f25a0d.png)
After some seconds, connects normally
No idea of what could be
@Jdochoa can you test if this occurs to you too?
Thanks

**Comment by Jdochoa** [comment]
works the same, will investigate the problem

**Comment by Jdochoa** [comment]
Hi @arvanus 
Fixed at https://github.com/Jdochoa/flamerobin/tree/FB3.

please help me with feedback

**Comment by arvanus** [comment]
Looks like it worked, just please fix your build, because the new build are using CMake do prepare build environment, so you need do edit CMakeList.txt
and add 
`		${SOURCEDIR}/metadata/package.cpp`

and
```

		${SOURCEDIR}/metadata/constants.h
		${SOURCEDIR}/metadata/package.h
```
to its respective places (any doubt I can help you) 
This way, the build will be successful at Github actions
Thanks!

**Comment by arvanus** [comment]
@Jdochoa can you pull request please?
I`ld like to  build a new snapshot this year 😃

**Comment by Jdochoa** [comment]
> @Jdochoa can you pull request please?
> I`ld like to build a new snapshot this year 😃

Today
