### ISSUE TITLE
Cannot search on Flamerobin Main Window Linux Mint

### ISSUE THREAD

**Issue by enclle** [mariuz/flamerobin#14]
Hello,

  I'm using FlameRobin on Linux Mint 18, "MATE" version, if I type just a letter in the search bar, it shows an error (see attached image), if I click in 'continue' it keeps showing the message, if I click 'stop' it closes.
 If I type in the search bar the letter 'a', it goes to a table that starts with 'a', but if I type 'v', it shows the error.
![erroflamerobin](https://user-images.githubusercontent.com/14343804/29777816-b1401276-8be3-11e7-84a2-61919d9498bc.png)

**Comment by cptx032** [comment]
The same in Ubuntu 16.04 LST

**Comment by mariuz** [comment]
What version of flamerobin ?

**Comment by cptx032** [comment]
I'm using version 0.9.3
![image](https://user-images.githubusercontent.com/12432805/34153133-c205cac4-e48f-11e7-8530-bb39e6379e9b.png)

**Comment by arvanus** [comment]
Hi @enclle I've found the error and will post a fix soon 
Until there please test the latest snapshot available and let me know if it's working
https://github.com/mariuz/flamerobin/releases/tag/0.9.3.2

**Comment by arvanus** [comment]
Fixed, please download source build and test
Thanks
