### ISSUE TITLE
Hide "System Packages" and "System Domains" nodes

### ISSUE THREAD

**Issue by luronumen** [mariuz/flamerobin#146]
Could you add the possibility of hiding **System Packages** and **System Domains** just like already happen with **System Tables** and **System Roles**?

![SystemObjects](https://user-images.githubusercontent.com/8019466/103910023-1da3bb80-50e3-11eb-9602-005d1ca6aa79.PNG)

**Comment by arvanus** [comment]
Done, please update and test (and close this issue if everything is OK)

**Comment by Jdochoa** [comment]
Hi all.
I will work in a new node with all system nodes.

**Comment by luronumen** [comment]
Hi @arvanus

Could you please generate a test build containing this fix to me test it?

Hi @Jdochoa 

I think that System Roles already exist:

![FlameRobin_System](https://user-images.githubusercontent.com/8019466/104013758-adec0a00-5190-11eb-9351-3bd16783f687.PNG)

BTW can you change the following nodes names:
- System roles to **System Roles**
- System table to **System Tables**
- System domains to **System Domains**

**Comment by arvanus** [comment]
https://github.com/mariuz/flamerobin/releases/tag/0.9.3.6
Download and test please

**Comment by arvanus** [comment]
![image](https://user-images.githubusercontent.com/8182958/104015423-6024d100-5193-11eb-9207-48dbb811afd8.png)

**Comment by luronumen** [comment]
Hi @arvanus 

I just retest this issue and now works perfect!

Thank you very much for the fix!
