### ISSUE TITLE
Newly created function is not displayed

### ISSUE THREAD

**Issue by pgiacomo69** [mariuz/flamerobin#158]
Flamerobin 0.9.3.6 Snapshot, Firebird 3.0.7
Steps to Reproduce:
- Create a new function
The function is not displayed in Flamerobin, to see it, disconnect and connect from db

**Comment by luronumen** [comment]
Hi @pgiacomo69 ,
 
Is this issue still reproducible in [0.9.3.8 Snapshot](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.8) version?

**Comment by arvanus** [comment]
I've tested it here, it shows when creating, but doesn't removes when deleting

**Comment by luronumen** [comment]
> I've tested it here, it shows when creating, but doesn't removes when deleting

Exactly @arvanus 
I have also mentioned this issue here #182

lets keep this issue open for while.

Best Regards,
Luciano

**Comment by luronumen** [comment]
Hi @pgiacomo69 

Could you please retest this issue on [FlameRobin 0.9.3.12](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.12) and close it if it is no longer reproducible?

Thanks in advance,
Luciano

**Comment by pgiacomo69** [comment]
> Hi @pgiacomo69
> 
> Could you please retest this issue on [FlameRobin 0.9.3.12](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.12) and close it if it is no longer reproducible?
> 
> Thanks in advance, Luciano

It's OK now, thanks for your effort!
