### ISSUE TITLE
Assertion error when pressing down arrow key while browsing data of an empty table

### ISSUE THREAD

**Issue by cptx032** [mariuz/flamerobin#16]
When clicking in a table to browser the data, if table is empty and I press down arrow key FlameRobin throws an error:

![image](https://user-images.githubusercontent.com/12432805/34040064-ea4c6924-e170-11e7-9f69-b900c0f352e2.png)

I'm using Ubuntu 16.04 LTS x64

**Comment by arvanus** [comment]
Hi, please test the latest snapshot available and let me know if it's working
https://github.com/mariuz/flamerobin/releases/tag/0.9.3.2

**Comment by luronumen** [comment]
Hi @cptx032 ,
 
Is this issue still reproducible in [0.9.3.8 Snapshot](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.8) version?
