### ISSUE TITLE
Add support Idendity column for Server version '3'

### ISSUE THREAD

**Issue by Zeki-Gursoy** [mariuz/flamerobin#164]
Firebird server 3 support idendity column now. Please could you add or this property. 

Doc. ref. : https://firebirdsql.org/file/documentation/release_notes/html/en/3_0/rlsnotes30.html#rnfb30-ddl-identity

**Comment by arvanus** [comment]
Hello @Zeki-Gursoy 
This functionality is ready for testings and will be available in the next snapshot in the next days!
Thanks for using Flamerobin!
