### ISSUE TITLE
Unable to change Field Datatype

### ISSUE THREAD

**Issue by pgiacomo69** [mariuz/flamerobin#165]
Right click a Field in browser, select "Properties", "CHAR" is always shown as Datatype and you are unable to change it..
If the Field Datatype is "CHAR", length is not shown and you trying change it throws an error. 

![Immagine 2021-02-03 101844](https://user-images.githubusercontent.com/1887236/106725369-95dd9e00-6609-11eb-971b-805863a74f23.jpg)
![Immagine 2021-02-03 102001](https://user-images.githubusercontent.com/1887236/106725388-9e35d900-6609-11eb-8a30-d39ddfd37680.jpg)

**Comment by arvanus** [comment]
Hello, can you send a print of your Flamerobin version?
Go to menu Help->About
something like this:
![image](https://user-images.githubusercontent.com/8182958/106751996-b527fb80-6608-11eb-8bd4-ae8c6756470e.png)

**Comment by arvanus** [comment]
@Jdochoa can you take a look if it`s a regression from #71 #156  #164

**Comment by pgiacomo69** [comment]
Hello, It’s 375bec5f, x64, FB 3.0.7

**Comment by Jdochoa** [comment]
> 
> 
> @Jdochoa can you take a look if it`s a regression from #71 #156 #164

It fixed in #156

**Comment by arvanus** [comment]
My fault, I hadn't the time to pull and publish a new snapshot

**Comment by Jdochoa** [comment]
> 
> 
> My fault, I hadn't the time to pull and publish a new snapshot

Please, wait a few days and we will include the new icons

**Comment by luronumen** [comment]
@Jdochoa
The RedExpert recently published more icons for the other missing objects.
For more details please chec this link: https://github.com/red-soft-ru/redexpert/tree/master/guide/img

**Comment by pgiacomo69** [comment]
Ok with 0.9.3.8
