### ISSUE TITLE
Idea - web ui

### ISSUE THREAD

**Issue by pwypustek** [mariuz/flamerobin#168]
Hi,
What do you think about adding a web UI variant for flamerobins like pgAdmin 4?
https://www.pgadmin.org/try/

In this variant, the flamerobin will run as a service and the web interface will be separate from the backend of the flamerobin.
what do you think?

**Comment by arvanus** [comment]
You can look at:
https://github.com/mariuz/firebirdwebadmin

**Comment by luronumen** [comment]
@pwypustek 

Could you close this issue since there is already a web UI solution for it?
