### ISSUE TITLE
New releases 

### ISSUE THREAD

**Issue by fernandobatels** [mariuz/flamerobin#17]
Hi @mariuz, i was looking on https://github.com/mariuz/flamerobin/releases and last release is from Mar / 2016, but commits / merges like https://github.com/mariuz/flamerobin/commit/6a6dd4da96f3e35d35dfb9b909f7587912e0375f, from pull request #8, not are "avaliable for download/use" without build from source.

Are any plans to next release?

If need, I can help writing release note, test changes since https://github.com/mariuz/flamerobin/releases/tag/0.9.3.1 or writing code :)

**Comment by luronumen** [comment]
Could someone generate a new build of FlameRobin for Windows with the latest version of the source code?
The last project commit was on Jan 25, 2018 and we are missing a great opportunity to test this code on Windows.

Thanks in advanced,
Luciano

**Comment by mariuz** [comment]
new snapshot for testing is here , we will do later other ones https://github.com/mariuz/flamerobin/releases/tag/0.9.3.2

**Comment by luronumen** [comment]
- For the next version, let's focus on fixing all issues marked as "bug".
- When we generate the next version, let's optimize the executable in size, speed, etc.
- I will continue here helping with testing and reporting defects found in the latest version of Flame Robin.

Best Regards,
Luciano
