### ISSUE TITLE
FlameRobin 0.9.3.7 is taking much longer to connect to a database than the previous version 0.9.3.6

### ISSUE THREAD

**Issue by luronumen** [mariuz/flamerobin#181]
ACTUAL RESULT
- FlameRobin 0.9.3.7 is taking much longer to connect to a database than the previous version 0.9.3.6;
- The Not Responding screen remains for several seconds until it is able to connect to the database:

![NotResponding](https://user-images.githubusercontent.com/8019466/109951138-156b9500-7cbc-11eb-8685-c1527cfd859b.png)

EXPECTED RESULT:
- The time to connect to a database should be similar to the previous version

IMPORTANT NOTES:
- This issue is best seen on a high latency network.

**Comment by arvanus** [comment]
same here

**Comment by luronumen** [comment]
Hi @Jdochoa 

Did you get to find the root cause of this issue?

Best Regards,
Luciano

**Comment by Jdochoa** [comment]
> Hi @Jdochoa
> 
> Did you get to find the root cause of this issue?
> 
> Best Regards,
> Luciano

I work on this.

**Comment by luronumen** [comment]
> > Hi @Jdochoa
> > Did you get to find the root cause of this issue?
> > Best Regards,
> > Luciano
> 
> I work on this.

Thank you very much @Jdochoa !

**Comment by arvanus** [comment]
@Jdochoa can you take a look at this?

**Comment by Jdochoa** [comment]
Hi @arvanus, @luronumen 

I fix this, please view my repository

./jo

**Comment by arvanus** [comment]
Still freeze for remote DB

**Comment by luronumen** [comment]
> Hi @arvanus, @luronumen
> 
> I fix this, please view my repository
> 
> ./jo

Hi @Jdochoa 

Could you please generate a compiled version for me? I do not have the environment setup to compile the FlameRobin.

Thanks in advance,
Luciano

**Comment by Jdochoa** [comment]
Hi @arvanus.
Can you try this one? 

https://drive.google.com/file/d/1POLlDlhV-l9R3YCBYJ4maywFkd8tajeq/view?usp=sharing

Please.

./jo

**Comment by luronumen** [comment]
> Hi @arvanus @luronumen
> Can you try this one?
> 
> https://drive.google.com/file/d/1POLlDlhV-l9R3YCBYJ4maywFkd8tajeq/view?usp=sharing
> 
> Please.
> 
> ./jo

Hi @Jdochoa 

This issue is no longer reproducible on this version but the following regression (see issue #65 ) is happening:

![Capture](https://user-images.githubusercontent.com/8019466/118710735-11e4a600-b7f5-11eb-8681-5e072616696a.PNG)

**Comment by arvanus** [comment]
@Jdochoa fixed here
Sorry, I had messed the git repo and wasn't with the latest commit, it's not hanging now

**Comment by arvanus** [comment]
Please do a pull request :)

**Comment by luronumen** [comment]
Retest result on [FlameRobin 0.9.3.8 Snapshot](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.8): **Passed!**

Thank you very much for the fix!
