### ISSUE TITLE
Unable to drop functions

### ISSUE THREAD

**Issue by luronumen** [mariuz/flamerobin#182]
**ISSUE 1:**
- Unable to drop functions

![DropFunctions](https://user-images.githubusercontent.com/8019466/110203420-ed5f6b80-7e4c-11eb-9a43-2ac22f121e83.png)

**ISSUE 2:**
- The output parameter is listed before the input parameters. 

![InputParameters](https://user-images.githubusercontent.com/8019466/110203450-18e25600-7e4d-11eb-9c4a-fdf9b7a85941.PNG)

STEPS TO REPRODUCE THE ISSUES:

- ISSUE 1: Right Click a functions and select Drop option from context popup menu: Verify that _<< Drop SQL >>_ instructions is displayed instead of the SQL instructions for delete the function
- ISSUE 2: Check how the input and output parameters are listed in a function: verify the output parameter is listed before the input parameters. Note that in procedures this issue is not reproducible.

**Comment by Jdochoa** [comment]
- Issue 1: Fixed.
- Issue 2: I'm not sure of this,  in the rdb$function_arguments firebird define the result in position 0, and ISQL list the arguments in this order

**Comment by luronumen** [comment]
- Issue 1: Thanks for the fix. I will retest is in the next version ;)
- Issue 2: How the procedures detects if a parameter is in or out. May be is the same logic.

Thank you very much for all improvement that you are doing on FlameRobin!

Best Regards,
Luciano

**Comment by luronumen** [comment]
> * Issue 1: Thanks for the fix. I will retest it in the next version ;)
> * Issue 2: How the procedures detects if a parameter is in or out. May be is the same logic.
> 
> Thank you very much for all improvement that you are doing on FlameRobin!
> 
> Best Regards,
> Luciano

Hi @Jdochoa 

Retest result on [flamerobin.zip](https://github.com/mariuz/flamerobin/files/6542298/flamerobin.zip):

- Issue 1: Partial fixed! The functions is dropped but it is still listed on Functions node. User have to refresh the Functions node manually to the deleted functions be removed from the functions node
- Issue 2: It is still reproducible.

**Comment by Jdochoa** [comment]
Hi @luronumen 
Can you give me feedback on this or close it?
Please view the last commit on my repository.


Thanks 
./jo

**Comment by luronumen** [comment]
> Hi @luronumen
> Can you give me feedback on this or close it?
> Please view the last commit on my repository.
> 
> Thanks
> ./jo

Hi @Jdochoa 

Could you please generate a FlameRobin build for me for retest it?

Thanks in adevance,
Luciano

**Comment by arvanus** [comment]
@luronumen can you try this again please?
Thanks

**Comment by luronumen** [comment]
Hi @Jdochoa 

Retest result on [flamerobin-0.9.3.b236510a-setup-x64.exe](https://github.com/mariuz/flamerobin/releases/download/0.9.3.10/flamerobin-0.9.3.b236510a-setup-x64.exe):

- Issue 1: Partial fixed! The functions is dropped but it is still listed on Functions node. User have to refresh the Functions node manually to the deleted functions be removed from the functions node
- Issue 2: It is still reproducible.

**Comment by luronumen** [comment]
Retest result on [FlameRobin 0.9.3.12](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.12): **PASS**!
Thank you very much for the fix!

Best Regards,
Luciano
