### ISSUE TITLE
Cannot Declare UDF

### ISSUE THREAD

**Issue by pgiacomo69** [mariuz/flamerobin#187]
Trying to declare a newly UDF written by me:

declare external function F_SET_INTERSECT
cstring(255), cstring(255), cstring(1)
returns integer by value
entry_point 'SET_INTERSECT'
module_name 'GP_UDF';

Flamerobin hangs indefinitely on "Starting Transaction", previous Flamerobin  Version (January?) had same problem.
Declaring the UDF with iSql works succesfully, andthen the  UDF itself work as expected, 

FlameRobin 0.9.3 (git hash 78287cd4) Unicode, Win32
Server Version: WI-V3.0.7.33374 Firebird 3.0, 64 bit

**Comment by arvanus** [comment]
Confirm it's hangs here too in the latest source code
Both 32 and 64 bits

**Comment by pgiacomo69** [comment]
Ok with 0.9.3.8
