### ISSUE TITLE
Package.cpp not included in Makefile when building flamerobin 0.9.3.7 on OpenSuse 15.2

### ISSUE THREAD

**Issue by hhfiddelke** [mariuz/flamerobin#188]
When building flamerobin on OpenSuse 15.2 i got an error message that flamerobin could not be linked together because of missing symbols from "./src/metadata/package.cpp".
After some investigation i found out that "package.cpp" is not included in the Makefile. 
After adding a rule for the file manualy to the Makefile, the program compiled and is running.

**Comment by Jdochoa** [comment]
> 
> 
> When building flamerobin on OpenSuse 15.2 i got an error message that flamerobin could not be linked together because of missing symbols from "./src/metadata/package.cpp".
> After some investigation i found out that "package.cpp" is not included in the Makefile.
> After adding a rule for the file manualy to the Makefile, the program compiled and is running.


Hi @hhfiddelke 
You can attach the your makefile?

Thank you

**Comment by arvanus** [comment]
You also could use CMake to build

**Comment by hhfiddelke** [comment]
Attached you see the the Makefile created by  configure.

I added:
558a559,561
> flamerobin_package.o: $(srcdir)/src/metadata/package.cpp $(FLAMEROBIN_ODEP)
>       $(CXXC) -c -o $@ $(FLAMEROBIN_CXXFLAGS) $(srcdir)/src/metadata/package.cpp
> 

to get it run.

[Makefile.txt](https://github.com/mariuz/flamerobin/files/6524136/Makefile.txt)
