### ISSUE TITLE
Question: Installing in El Captain

### ISSUE THREAD

**Issue by typevitor** [mariuz/flamerobin#2]
Hi. I Have a mac with OS el captain and it does not seen to be possible installing flamerobin.
I tried with the dmg file (0.9.2) in the download section on the web-site

I need to do something do make it work?

**Comment by Tomas2D** [comment]
**You have to compile your own version of Flamerobin.**

_Steps below should help you :-)_

## **How to compile Flamerobin on Mac OS X 10.11**

// Before we can get into compiling
- Download Mac OS X SDK's (https://github.com/phracker/MacOSX-SDKs), after download move that SDK into /Developer or your prefered folder
- Compiled wxWidgets version 3.0.2 installed with -prefix=/opt/wxconfig (optional)
- Need to install Homebrew (http://brew.sh/)
- After downloading and installing Homebrew run following commands:

```
brew install boost
brew install autoconf
```

**// Configuration command**
- need to add additional flag for compiler which is   -stdlib=libstdc++   Older version of Mac OS X were using libstdc++ for compiling, but from version MAC OS X 10.9(June 10, 2013) this default settings has been changed to libc++

**// Final configuration**
`../configure --disable-debug --disable-dependency-tracking CFLAGS="-stdlib=libstdc++ -mmacosx-version-min=10.11 -isysroot /Developer/SDKs/MacOSX10.11.sdk" LDFLAGS="-stdlib=libstdc++ -Wl,-syslibroot,/Developer/SDKs/MacOSX10.11.sdk -Wl,-macosx_version_min -Wl,10.11" CXXFLAGS="-stdlib=libstdc++ -mmacosx-version-min=10.11 -isysroot /Developer/SDKs/MacOSX10.11.sdk" --with-wx-config=/opt/wxwidget3/bin/wx-config`

**// After configuration**
`make`


Tested on MAC OS X 10.11

**Comment by mariuz** [comment]
Updated instructions to build here https://github.com/mariuz/flamerobin/blob/master/BUILD.txt#L182
