### ISSUE TITLE
Functions are not listed as objects that depend on it

### ISSUE THREAD

**Issue by luronumen** [mariuz/flamerobin#202]
ACTUAL RESULT:
 - Functions are not listed as objects that depend on it

EXPECTED RESULT
 - Functions should also listed as objects that depend on it

STEPS TO REPRODUCE THE ISSUE

1- Create a function that depends on a table (ex: _M_PERMISSION_CODE function_ depends on _PERMISSIONS table_):

![FUNCTION](https://user-images.githubusercontent.com/8019466/120536469-8bb28d00-c3ba-11eb-8674-1ba833a98537.png)

2- Open the _PERMISSIONS table_ and check the objects that depends on it:  Functions are not listed as objects that depend on it

![TABLE](https://user-images.githubusercontent.com/8019466/120536725-cd433800-c3ba-11eb-892a-33858d89b779.png)

**Comment by arvanus** [comment]
@Jdochoa can I publish a new snapshot with your current pull request? (I just fixed this issue too) 
Thanks

**Comment by Jdochoa** [comment]
> 
> 
> @Jdochoa can I publish a new snapshot with your current pull request? (I just fixed this issue too)
> Thanks

Yes 
Can you check #190,  before? 

./jo

**Comment by luronumen** [comment]
Retest result on [FlameRobin 0.9.3.8 Snapshot](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.8): **Passed!**

Thank you very much for the fix!
