### ISSUE TITLE
LogicException asking properties of a procedure

### ISSUE THREAD

**Issue by mirmalag** [mariuz/flamerobin#207]
I'm working on a FB 2.1 database.
I do right-click, Properties. An error dialog pops up:
Unhandled Error in FlameRobin
*** IBPP::LogincException ***
Context: Row::IsNull
Message: Variable index out of range

Re-doing the same operation a fatal error occurs.

It happens with any database I can try on. 
All of them are ODS 11.1 (Firebird 2.1) and gfix doesn't reveal problems on any.

Mirco

**Comment by arvanus** [comment]
Occurs the same to me with Fb1.5 database

**Comment by mirmalag** [comment]
More on the matter: the same exception is raised when the code completion searches for a procedure.
It happens even with a barely minimal database like this.
[test_case_tabpriv.zip](https://github.com/mariuz/flamerobin/files/6608987/test_case_tabpriv.zip)
I guess some code doesn't play well with old ODSes.

Mirco

**Comment by arvanus** [comment]
Please, update https://github.com/mariuz/flamerobin/releases/tag/0.9.3.9 and try again

**Comment by mirmalag** [comment]
It works perfectly now.
Thank you.

Mirco
