### ISSUE TITLE
Error loading package's functions/procedures properties

### ISSUE THREAD

**Issue by afarias-br** [mariuz/flamerobin#208]
Field RDB$PACKAGE_NAME misses it's source table alias (see attached image) -- using 64bits 0.9.3.8 Snapshot, Firebird 3.0.4 (64bits Windows)

![image](https://user-images.githubusercontent.com/58704334/121199775-956c4280-c849-11eb-827c-e6718b5653dd.png)

**Comment by arvanus** [comment]
Please, update https://github.com/mariuz/flamerobin/releases/tag/0.9.3.9 and try again

**Comment by afarias-br** [comment]
> Please, update https://github.com/mariuz/flamerobin/releases/tag/0.9.3.9 and try again

Working perfect now. Thanks @arvanus

**Comment by luronumen** [comment]
Hi @afarias-br 

Could you please close this issue?

thanks in advance,
Luciano
