### ISSUE TITLE
(external) OpenHub project description outdated

### ISSUE THREAD

**Issue by Wolf-at-SO** [mariuz/flamerobin#21]
Hi @mariuz, 
Sorry if this isn't the right place: can you please have a look into https://www.openhub.net/p/flamerobin I'd love to see the current project state there. Maybe you are interested as well. It seems to be possible to login with a GitHub account on [OpenHub](https://en.wikipedia.org/wiki/Open_Hub). Thanks in advance :)

**Comment by mariuz** [comment]
thanks i have updated with github source link

**Comment by Wolf-at-SO** [comment]
Thanks a lot, but it seems that there is another step to do (*reopen* ?). I'm not sure if this is only a temporary issue: the commits on github are still not considered. The "last commit" currently shown is this old one:
https://www.openhub.net/p/flamerobin/commits/425961420
As I remember from the past, it was possible to *add* repositories, not only replace one by another. That open source projects sometimes move is realized by Ohloh/OpenHub.

**Comment by mariuz** [comment]
it will take a while to reindex i guess

**Comment by Wolf-at-SO** [comment]
I (hopefully) see :) 
... have you maybe a reference at hand where OpenHub describes their indexing policy, I had looked for it but wasn't successful yet.

**Comment by mariuz** [comment]
all i can say it will take a while , they are very slow at it
