### ISSUE TITLE
Field Editor in Grid assumes numeric input always as decimal values

### ISSUE THREAD

**Issue by pgiacomo69** [mariuz/flamerobin#210]
When editing a value  in grid, if you write only numeric digits then the value is considered to be float regardless of column type, so, if you put '1' in a varchar field, the field is updated with "1.000000" value. So it is impossible to edit a varchar field if you intend to write only numeric chars. Edit integer fields it is impossible at all, since it raises an error "Invalid Integer Numeric Value".
The error is present from 0.9.3.8 version, and still present with 0.9.3.9. In the screenshot, I'm trying to write "1048" in  "COD" colum, defined as Varchar(4).

![Immagine 2021-06-09 140526](https://user-images.githubusercontent.com/1887236/121353121-cde54c80-c92d-11eb-9fd6-60bfd2f09385.jpg)

**Comment by pgiacomo69** [comment]
Has  anyone other encountered this issue? Can be caused by the code at https://github.com/mariuz/flamerobin/blob/3e169310f86434a40d20b39f998734a994b5d993/src/gui/controls/DataGridRows.cpp#L2100 ?

**Comment by Jdochoa** [comment]
> 
> 
> Has anyone other encountered this issue? Can be caused by the code at
> 
> https://github.com/mariuz/flamerobin/blob/3e169310f86434a40d20b39f998734a994b5d993/src/gui/controls/DataGridRows.cpp#L2100
> ?

Hi @pgiacomo69 .

Please, review the solution at https://github.com/Jdochoa/flamerobin.git

./jo

**Comment by pgiacomo69** [comment]
I'll have to wait for a new snapshot, since I haven't set the build environment. There is a guide to setup it? The doc is iutdated.

**Comment by Jdochoa** [comment]
> 
> 
> I'll have to wait for a new snapshot, since I haven't set the build environment. There is a guide to setup it on windows with VS? The doc is outdated.

Use this. [flamerobin.zip](https://github.com/mariuz/flamerobin/files/6641786/flamerobin.zip)

./jo

**Comment by fperana** [comment]
This seems to be solved in the latest snapshot 0.9.3.10. Maybe it should be closed.
