### ISSUE TITLE
FlameRobin only shows the first 1024 characters of a BLOB TEXT field

### ISSUE THREAD

**Issue by luronumen** [mariuz/flamerobin#213]
ACTUAL RESULT
- FlameRobin only shows the first 1024 characters of a BLOB TEXT field

EXPECTED RESULT
- FlameRobin should show all characters from a BLOB TEXT field

STEPS TO REPRODUCE THIS ISSUE
- Run the following EXECUTE BLOCK with a long TXT_BLOB longer than 1024 characters: verify that the FlameRobin only shows the first 1024 characters.

SET TERM ^;
EXECUTE BLOCK
RETURNS (TXT_BLOB BLOB CHARACTER SET WIN1252)
AS
BEGIN
TXT_BLOB='<Write long text longer than 1024 characters here>';
SUSPEND;
END^
SET TERM ;^

**Comment by arvanus** [comment]
Not a problem
Fr just fetches the first N bytes in the grid, to get all the bytes you need to properly open the BLOB
Also, you can increase this 1k size at View->Preferences->Data Grid

![image](https://user-images.githubusercontent.com/8182958/122757715-5806ac80-d26e-11eb-9797-106167b30e53.png)

**Comment by arvanus** [comment]
Please close the issue if it's OK

**Comment by luronumen** [comment]
Hi @arvanus 

You are completely right!
closing it!

Best Regards,
Luciano
