### ISSUE TITLE
Import patchs from IBPP in SourceForge

### ISSUE THREAD

**Issue by arvanus** [mariuz/flamerobin#215]
https://sourceforge.net/p/ibpp/patches/8/
Needs to review first
```

Unicode projects. 
Please correct windows function names to avoid problems with unicode default characterset projects.
Thanks.
```

**Comment by Jdochoa** [comment]
Hi @arvanus 

It looks good, I am going to apply it in my repository and do tests 

./jo

**Comment by arvanus** [comment]
@Jdochoa it's OK, I can do this too, also I'm planning to implement reading server log file too:
https://sourceforge.net/p/ibpp/patches/6/

**Comment by luronumen** [comment]
Hi @arvanus 

Could you please retest this issue on [FlameRobin 0.9.3.12](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.12) and close it if it is no longer reproducible?

Thanks in advance,
Luciano
