### ISSUE TITLE
Confusing phrasing on Flamerobin home page

### ISSUE THREAD

**Issue by Wolf-at-SO** [mariuz/flamerobin#22]
On the Flamerobin homepage, there we still read
> Flamerobin github mirror
18 November 2015 There is a github mirror where you can send pull requests for flamerobin https://github.com/mariuz/flamerobin. 

But I think this needs an update to not confuse people. It's still possible to edit the code on SF, but I don't believe that the team was split up at the time you started FR development on GitHub.

**Comment by arvanus** [comment]
Is SF code still used?

**Comment by mariuz** [comment]
it will be used as mirror and legacy

**Comment by mariuz** [comment]
I will modify the text , now these days development moved to github
