### ISSUE TITLE
Build/installation on macOS Big Sur 11.4

### ISSUE THREAD

**Issue by Tomas2D** [mariuz/flamerobin#220]
Hey, I am trying to set up Flamerobin on my macOS Big Sur 11.4. 🍏

The compilation process went fine, except small edit of `CMakeLists.txt`, where I needed to do this
```
if (UNIX)
        if (NOT APPLE) # ADDED THIS CONDITION
                # UNIX (Linux) specific details
                list(APPEND SOURCE_LIST
                        ${SOURCEDIR}/gui/gtk/StyleGuideGTK.cpp
                )
        endif (NOT APPLE)
        
        add_definitions(-DIBPP_LINUX)
        add_definitions(-DFR_INSTALL_PREFIX="${CMAKE_INSTALL_PREFIX}")
        # Need to link the fbclient lib in *nix systems
        list(APPEND FR_LIBS -lfbclient)

        # Create the revision include file
        execute_process(
                COMMAND "${CMAKE_SOURCE_DIR}/update-revision-info.sh"
                WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
        )

        # Util script to help run FR in build dir
        file(COPY utils/run_flamerobin.sh  DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
        
endif (UNIX)
```

then it compiles successfully, but after running `make install`, the Flamerobin is installed to `/usr/local/bin` which is not desired on macOS, it should be `Flamerobin.app`, which contains everything inside it (this was working in older versions of Flamerobin, probably before CMake). 

I see that you have a configuration for it in Makefile.in, but it looks like that it was not executed at all.
https://github.com/mariuz/flamerobin/blob/1b4bafbfdc34ee14ed1156229535bb113074670c/Makefile.in#L280-L311

Can you please give me some advice on how to edit CMakeLists/Makefile to achieve it? 
Thanks.

**Comment by arvanus** [comment]
Hello @Tomas2D, sorry, I'm not used to work with Mac
I know that @blumf  did the port to Cmake, and he asked for mac users here #120 

You can take a look at: https://github.com/mariuz/flamerobin/blob/1b4bafbfdc34ee14ed1156229535bb113074670c/CMakeLists.txt#L360-L378
And https://github.com/mariuz/flamerobin/blob/1b4bafbfdc34ee14ed1156229535bb113074670c/CMakeLists.txt#L406
if it's this lines to improve, and you know how do change, can you make a pull with the fix?

**Comment by blumf** [comment]
After a quick bit of Googling, maybe the changes in PR #221 might help.

Tightened up the platform detection (plain 'UNIX' covers Linux/BSD/etc. and Apple)
Used MACOSX_BUNDLE properties too, hopefully, they do the right thing.

Working in the dark here, does it make any sense to you @Tomas2D ?

**Comment by Tomas2D** [comment]
Hey, thanks for a quick reply, I was quite busy, but today I had time to look at it and created a pull request with related changes. Quite a pain to make it work I must say 😄  

But thanks for getting me on the right track and for working on this software.

**Comment by Tomas2D** [comment]
We can probably close this for now, or?
