### ISSUE TITLE
Invalid integer numeric value

### ISSUE THREAD

**Issue by mrjohnr** [mariuz/flamerobin#227]
HI, with latest snapshot 0.9.3.9,when I try to edit smallint/bigint values using grid I got always the error: Invalid integer numeric value
in screenshot I put 1 instead of 0 for TIP column,for decimal works
thanks

![img](https://user-images.githubusercontent.com/11148089/133392148-2373007c-393a-4666-adfa-c3554a777409.png)

**Comment by fperana** [comment]
Same there. It also happens when editing String fields when the value contains only digits.
The produced SQL is something like `set STRING_FIELD = '518.000000'`

**Comment by fperana** [comment]
Hi, is it possible to have a new snapshot compiled with at least the current fixed bugs? It's quite frustrating to use two versions of flamerobin, the last to have support for data type in FB3 and one older to being able to edit numeric and string fields.

**Comment by mrjohnr** [comment]
Indeed very ugly bug,makes new version of Flame Robin unsless for FB>2.5

**Comment by arvanus** [comment]
Please update to the latest snapshot (0.9.3.10) and try again, if working please close this issue.
Thanks

**Comment by mrjohnr** [comment]
for me seems it is working
