### ISSUE TITLE
FlameRobin search for fbclient.dll in the wrong place for Firebird 4.0 - there is no BIN directory in Firebird 4.0 install folder

### ISSUE THREAD

**Issue by abzalov** [mariuz/flamerobin#229]
In Firebird 4.0, all executables are located in the root directory of its installation, including fbclient.dll.

As a temporary fix, you can create the symlink to the BIN folder:
  mklink /D "C:\Program Files\Firebird\Firebird_4_0\bin" "C:\Program Files\Firebird\Firebird_4_0"

**Comment by luronumen** [comment]
Hi @abzalov 

Could you please retest this issue on [FlameRobin 0.9.3.12](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.12) and close it if it is no longer reproducible?

Thanks in advance,
Luciano
