### ISSUE TITLE
Can't build on Ubuntu 20.04.3

### ISSUE THREAD

**Issue by franciscoernestoteixeira** [mariuz/flamerobin#232]
Hello, I followed all steps in this link:

http://www.flamerobin.org/dokuwiki/wiki/howtobuildonubuntudebian

But in make step a error is happing.

Log file is complete and attached.

[flamerobin_202110140015.log](https://github.com/mariuz/flamerobin/files/7342732/flamerobin_202110140015.log)

Thank you!

**Comment by mariuz** [comment]
please pull  current version from , it should be fixed

https://github.com/mariuz/flamerobin/commit/0cde69f443b8bcfdd2f9d24314afcf0fb3f78932
