### ISSUE TITLE
Error editing 64 bit Value

### ISSUE THREAD

**Issue by hafedh-trimeche** [mariuz/flamerobin#235]
Hello,
Version: 0.9.3 Unicode x64.
Please note error generated when trying to set a 64bit integer value to 0 (MODULEVERSION / bigint).

Best regards.
![flamerobin_LizJzCwWSS](https://user-images.githubusercontent.com/988584/143093563-8bfd0c4f-d0bf-4441-8cdb-1fa2f0a1ccea.png)

**Comment by arvanus** [comment]
Couldn't reproduce error here, please update to the latest snapshot (0.9.3.10) and try again, if working please close this issue.
Thanks

**Comment by hafedh-trimeche** [comment]
Hello,

Problem solved with the last version (0.9.3.b236510a).

Best regards.
