### ISSUE TITLE
FlameRobin has problems with the insertion of umlauts

### ISSUE THREAD

**Issue by ralfiii** [mariuz/flamerobin#237]
I have a table with a field

`VALCONTENT BLOB SUB_TYPE TEXT SEGMENT SIZE 80`

When I browse the table, right click on an entry, select "Edit blob" the content is shown.
If I enter "normal" test ("Hello world"), I can click "Save" and things work.
If I use umlauts ("Hällö Wörld"), I get an error message:

`IBPP::SQLExcetption, Contenten: Statement: Execure (Update MyTable set foo= ? where ..." Message isc_dsql_execute2 failed, -303, incompatible column, malformed string`

Am I doing something wrong or is FlameRobin not able to handle UTF8?

I am using Firebird 4.0 64bit, FlameRobin 0.9.3 Unicode x64 (all just downloaded). Extracting the DDL with "iSQL -o" shows in the first line
`/* CREATE DATABASE 'E:\foo.fdb' PAGE_SIZE 16384 DEFAULT CHARACTER SET UTF8; */`

I originally reported this on https://stackoverflow.com/questions/70217294/does-flamerobin-have-problems-with-the-insertion-of-umlauts/70223841#70223841
Mark Rotteveel could reproduce it and asked me to report the issue here. Done.

**Comment by arvanus** [comment]
Please update to the latest snapshot (0.9.3.10) and try again
Thanks

**Comment by ralfiii** [comment]
Works now. Thanks.
