### ISSUE TITLE
Correct Timestamp format in generated SQL code for FB4 compatibility

### ISSUE THREAD

**Issue by fperana** [mariuz/flamerobin#240]
Hi.

This is somewhat related to issue #178.

Generated SQL code that contains Timestamps (i.e. when updating a row in a table with a Timestamp field in the Primary Key) is formatted with a colon between the date and time portions, which isn't supported by FB4.

![image](https://user-images.githubusercontent.com/24318949/145799976-0235dad2-a9b8-404b-ada1-562641050d85.png)

That colon should be removed, as the timestamp format shouldn't contain it (even in FB < 4).

**Comment by arvanus** [comment]
Hello, yes, totally related.
For you can change your config at "View->Preferences->Data Grid->Timestamp format"

**Comment by fperana** [comment]
I've already changed the display format, but unfortunately this doesn't affect the inner workings (the error I've posted proves this).

This is my current config:
![image](https://user-images.githubusercontent.com/24318949/145819873-76657921-6289-4ec0-a3ba-142f33aaaeb9.png)

**Comment by fperana** [comment]
Great fix, thanks!

I'll wait for a new snapshot build ;)

**Comment by arvanus** [comment]
Done :)
