### ISSUE TITLE
Flamerobin throws LoginException

### ISSUE THREAD

**Issue by maigo66** [mariuz/flamerobin#246]
Hi, 
I downloaded FlameRobin and get errors on login to an exiting database (see attatched image).

1: I copied the fmembed.dll (2.5.9.27139) to the application folder and renamed it to fbclient.dll, after click connect to existing db I get the error "Can´t find or load FBCLIENT.DLL or GDS32.DLL".

2: I copied the fmembed.dll (1.5.3.4870) to the application folder and renamed it to fbclient.dll, after click connect to exiting db I get the error "Entry-point fb_interpret not found".

![FlameRobin_Errors](https://..user-images.githubusercontent.com/20399341/151975524-d347d540-fd4e-455e-9e80-4335a7d6a9ed.png)

**Comment by arvanus** [comment]
If I understood correctly you are trying do access a database directly (embedded) is it right?
Have you tried to use FBCLIENT.DLL directly with a running Fb server?

**Comment by maigo66** [comment]
Thx for your post! 
I managed to create a db (which I want to access also via FlameRobin) and tables within the db with the fbemded.dll with a .net c# application.

**Comment by arvanus** [comment]
Are you sure you used 32bits DLL with 32 bits Flamerobin (or 64bits DLL with 64 bits Fr)? 
I just downloaded embedded DLL and it worked fine

**Comment by maigo66** [comment]
Flamerobin 0.9.3 is installed in x86 program files folder and yes, I tested with32 bit dlls.

**Comment by maigo66** [comment]
can you please give me the link to the 32 bit version?

**Comment by arvanus** [comment]
did you copied all the DLLs and folders in the zip file directly to Flamerobin folder?
Also, try not to rename the DLL, Flamerobin uses IBPP that first try to load `fbembed.dll` and if not found, will use `fbclient.dll`

**Comment by maigo66** [comment]
No I copied only the fbembed.dll and renamed it to fbclient.dll.

**Comment by arvanus** [comment]
So this is your error, try again and say if it worked

**Comment by maigo66** [comment]
ok, now I copied all files to the folder and get the following error:
________________________________

*** IBPP::SQLException***
Context: Database: Connect
Message: isc _attach database failed
SQL Message : -902
Unsuccessful execution caused by a system error that precludes successful execution of subsequent statements Engine Code : 335544721 Engine Message:
Unable to complete network request to host "127.0.0.1"
Failed to establish a connection.

**Comment by maigo66** [comment]
"localhost" also does not work...

**Comment by arvanus** [comment]
You must keep Hostname and port empty to force embedded connection
![image](https://user-images.githubusercontent.com/8182958/151984417-a068e6f8-a23d-4391-8553-0a1a86f8fd09.png)

**Comment by maigo66** [comment]
Hey!!! IT WORKED!!! YOU ARE MY HERO OF TODAY ;)

**Comment by maigo66** [comment]
1 additional question: which FirebirdSql.Data.FirebirdClient version do I have to use to deal with the fbembed.dll 2.5.9.27139? (I struggle accessing the db created with flamerobin via c# app.) Thx!

**Comment by arvanus** [comment]
Sorry, don't use C#, can't help

**Comment by maigo66** [comment]
ok, understand! But I wonder which version of the FirebirdSql.Data.FirebirdClient fits to which fbemed?!
When I create a db from code it works and I can access via Flamerobin. Whereas when I create a db in Falmerobin, I can`t access from code... FR uses a fbembed from 2019 and my code from 2004, there is a great gap, I know, but I could not find a FirebirdSql.Data.FirebirdClient library that works with 2019 version... Thx again!

**Comment by borgogelli** [comment]
> Hey!!! IT WORKED!!! YOU ARE MY HERO OF TODAY ;)

@maigo66 please share also a screenshot about the db config
