### ISSUE TITLE
fbclient.dll not found..

### ISSUE THREAD

**Issue by mrx23dot** [mariuz/flamerobin#247]
On
- win7 x64
- I installed client configuration from Firebird-4.0.1.2692-0-Win32.exe
- I've got 32bit  DLL here: C:\Windows\System32\fbclient.dll
- C:\Windows\System32\ is in my PATH
- restarted Flamerobin (flamerobin-0.9.3.e6015349-setup.exe 32bit)
- but it still complains:

![2022-02-06_135910](https://user-images.githubusercontent.com/4163396/152684388-46725d07-7f40-4c70-bb3a-8f5a7437d00f.jpg)

even after I put fbclient.dll next to "C:\Program Files (x86)\FlameRobin\flamerobin.exe"

Why is FlameRobin being so difficult?
I need the 32bit client library for my 32bit python.

**Comment by nLeonardt95** [comment]
On a 64bit system you have to put the 32 bit DLLs under syswow64 and not system32.
If the Windows runtimes are not installed, the "vcruntime140.dll" and "msvcp140.dll" from the Firebird directory must also be added to the EXE directory of Flamerobin. 
"msvcp140.dll" must be placed in the EXE directory of Flamerobin.

**Comment by mrx23dot** [comment]
Thanks for the reply, now I have 32bit dll at both places:
- C:\Windows\SysWOW64\fbclient.dll
- C:\Windows\System32\fbclient.dll

also copied these 32bit dlls here:
- C:\Program Files (x86)\FlameRobin\vcruntime140.dll
- C:\Program Files (x86)\FlameRobin\msvcp140.dll

restarted robin, same error msg.
Telling you this sw is haunted.

**Comment by mrx23dot** [comment]
It works okay if everything is 64bit, 
so I think the 32bit robin is looking for the dll at wrong place, it expects that the OS is also 32bit.

**Comment by nLeonardt95** [comment]
Are you sure you are using the 32-bit Flamerobin version and not the 64-bit?

I have no problem with both versions.

**Comment by mrx23dot** [comment]
Copying DLL next to exe solved it, easiest solution.
Might worth packing dll in installation, since it's already firebird specific app. Would solve a lot of rounds.
Thanks.
