### ISSUE TITLE
Change SQL statement editor's background color?

### ISSUE THREAD

**Issue by glubsy** [mariuz/flamerobin#25]
I'm not sure whether this is a question about GTK theming or an actual feature request.

It would be nice to be able to change the color scheme of the SQL statement window / editor. Especially the white background color which is very bright and not ideal for long hours of work. Changing the font colors would be needed as well then. 

Is this hardcoded in Flamerobin?  I suspect as much since the syntax highlighting has its own set of colors too. But perhaps this is possible through GTK theming? Not very familiar with this yet.

Running on Arch Linux, GTK theme is Adwaita Dark.

**Comment by glubsy** [comment]
Ok I guess it is hardcoded after all:
https://github.com/mariuz/flamerobin/blob/master/src/gui/ExecuteSqlFrame.cpp#L310

**Comment by luronumen** [comment]
Hi @glubsy ,
 
Could you please close this issue once this is marked as wontfix?

Thank in advance,
Luciano

**Comment by Jdochoa** [comment]
Do not close it, if you have patience it will come, if you close it I will forget 

./jo

**Comment by glubsy** [comment]
The problem not being fixed, I would not have closed this ticket myself anyway.

**Comment by luronumen** [comment]
> Do not close it, if you have patience it will come, if you close it I will forget
> 
> ./jo

ok @Jdochoa 

I thought this issue wouldn't be fixed because of the *wontfix* label. 

Best Regards,
Luciano
