### ISSUE TITLE
Incorrect trigger state display 

### ISSUE THREAD

**Issue by esdonis** [mariuz/flamerobin#252]
Hi

Does not visually show when a trigger is inactive.

**Comment by luronumen** [comment]
Hi @esdonis 

Could you please retest this issue on [FlameRobin 0.9.3.12](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.12) and close it if it is no longer reproducible?

Thanks in advance,
Luciano

**Comment by esdonis** [comment]
It has already been fixed
Thank you
