### ISSUE TITLE
Windows version won't build

### ISSUE THREAD

**Issue by PhilPJL** [mariuz/flamerobin#256]
Latest repo dev or master branch gives

![image](https://user-images.githubusercontent.com/271656/161067248-673b4cd9-cae1-494a-9a62-43995a239c96.png)

when trying to build with VS2019.

and this

![image](https://user-images.githubusercontent.com/271656/161067444-55b7bc7f-0e06-4ac6-bd47-0e39156d9557.png)

when trying to build with VS2022.

**Comment by Jdochoa** [comment]
Hi
Please read https://github.com/mariuz/flamerobin/blob/master/BUILD.txt

./jo
