### ISSUE TITLE
Flamerobin corrupt loaded sql file when saved again (empty)

### ISSUE THREAD

**Issue by livius2** [mariuz/flamerobin#259]
Flamerobin corrupt loaded sql file when saved again. 
I do not know if this is becaouse of encodding?
But if you load file and change anything and press save, it will empty the file on the HDD :-(
Try attached file (tested with newest filamerobin)

[Przepięcie danych sprawozdania na nowe sprawozdanie2.txt](https://github.com/mariuz/flamerobin/files/8876909/Przepiecie.danych.sprawozdania.na.nowe.sprawozdanie2.txt)

**Comment by arvanus** [comment]
Hi, sorry but I couldn't replicate your problem. Can you reproduce and detail it to me?
I tried with 32 and 64 bits file

**Comment by arvanus** [comment]
Just to reference the code, I think it could have an else statement if not saved, but this is not the cause of your problem
https://github.com/mariuz/flamerobin/blob/de8f182d405bba002056d7756be27fbe22e0d23d/src/gui/ExecuteSqlFrame.cpp#L1347-L1368

**Comment by livius2** [comment]
Looking at your attached code, it looks like error only possible inside 
`styled_text_ctrl_sql->SaveFile(filename)` - if you have source code of that control, then maybe possible to catch this.
But first you must replicate problem on your side :/

**Comment by arvanus** [comment]
maybe, have you tried in another partition or folder? (assuming some crazy permission error)
Also, if you "save as" overwriting or not the file does it work?
I cant try now, but as soon as I can I'll give you feedback

**Comment by arvanus** [comment]
`styled_text_ctrl_sql->SaveFile(filename)` is from wxWidget

**Comment by livius2** [comment]
>> maybe, have you tried in another partition or folder? 
no, if i without load file and write something it is saved without problems

>> Also, if you "save as" overwriting or not the file does it work?

tested now option "save as" new file is created but it is empty :/
So something in this file made this control(wxWidget) to save nothing :/
If it will not erease my file it will be "less problematic" but good that i have script backup from previous day :)

**Comment by arvanus** [comment]
hello, again, can't reproduce here
Just out of curiosity, does your SQL history work?
Also, have you tried to save a simple 1-2 rows SQL, also in a new folder/partition?

**Comment by livius2** [comment]
Hi, yes sql history is working ok.
I have tried this file on third computer and the same problem.

Any other scripts are working ok, but this one not. I am really interested in fixing the problem, as i like to still trust flamerobin as i have trusted it for years.

**Comment by arvanus** [comment]
> FlameRobin 0.9.3 (git hash [e601534](https://github.com/mariuz/flamerobin/commit/e6015349d37ce64830a71c193745464211594689)) Unicode (x64)

Yes, tried with exactly this one release, saved the file
Downloaded the file `Przepiecie.danych.sprawozdania.na.nowe.sprawozdanie2.txt`, at "Desktop", "D:\custonFolder\", "user\Documents\".
I opened in Fr with database charset NONE, UTF8 and ISO8859_1 (shouldn't matter but anyway I tried) inserted a space at line 20, saved, reopened and nothing

I'm looking for how to show error message from wxWidgets, as soon as I found (I'm not a wx expert) I'll publish a snapshot for you to try 
Thanks

**Comment by arvanus** [comment]
> I have tried this file on third computer and the same problem.

Just to be sure, have you tried using the file from this link you passed me? (downloaded and tried from this source, not "directly from your disk file"
https://github.com/mariuz/flamerobin/files/8876909/Przepiecie.danych.sprawozdania.na.nowe.sprawozdanie2.txt

**Comment by arvanus** [comment]
Please, try this setup, I add a simple error dialog
https://github.com/mariuz/flamerobin/commit/165463b66c645984c1f7a37891b1a9d651a05fa7
Download and test please:
https://github.com/mariuz/flamerobin/releases/tag/0.9.3.11%23259

**Comment by livius2** [comment]
Tested, but the dialog not show up.
But one more thing happened, for a second i have seen in the same location file with `.tmp` extension
with exact same size as my loaded file. Then it dissapear and the dialog was show to reload:
![image](https://user-images.githubusercontent.com/14888294/174250112-565ebd9d-6677-44b0-ad32-609d47d4a49a.png)
And main file go to empty size.
![image](https://user-images.githubusercontent.com/14888294/174250445-e6fe736e-6721-404a-9ea4-d4ae86ef5982.png)

**Comment by arvanus** [comment]
@livius2 can you try this snapshot?

https://github.com/mariuz/flamerobin/releases/download/0.9.3.11%23259/flamerobin-0.9.3.c3c51c4f-setup-x64.exe
Check this new option and try saving the file.

2 more tests to you try to save:
-Same content, different file name (simple and short ANSI file name)
-Same file name, different content (simple and short ANSI SQL text)

![image](https://user-images.githubusercontent.com/8182958/174646585-9fc0fc6c-1645-4b70-8dc4-fede545d825c.png)

**Comment by livius2** [comment]
"Use alternate save SQL file mothod" is working ok :)
No problem with saving this file and any modifications to it.

**Comment by livius2** [comment]
I have looked at your code and it looks safe to me. It can be used instead of saving from widget itself.
I suppose removing then option from config will be also good.

PS. i am really curious how save method look in widget itself that it can fail.
