### ISSUE TITLE
Problems reading from Google Drive File Stream (26.1.42.2151) on Windows 10 (1803)

### ISSUE THREAD

**Issue by jrcarlsen** [mariuz/flamerobin#26]
When trying to import a database located on DFS on Windows 10 Pro, the following error occurs:

```Connecting to server localhost...
Database restore started 14:54:11
Database restore canceled 14:54:11 due to IBPP exception:

*** IBPP::SQLException ***
Context: ServiceImpl::Wait
Message: isc_service_query failed

SQL Message : -901
Unsuccessful execution caused by system error that does not preclude successful execution of subsequent statements

Engine Code    : 336330817
Engine Message :
cannot open backup file G:\My Drive\Database.fbk
Exiting before completion due to errors
```

It makes no difference if the file is made available offline.

Opening the file in other applications works fine, copying it to a local drive and loading it works fine too.

Google Support was not helpful at all. My guess is that Flamerobin is using slightly non-standard ways of reading and writing files.

**Comment by arvanus** [comment]
Have you tried restoring directly from Firebird gbak.exe?

**Comment by arvanus** [comment]
So basically the problem occurred with "gbak" tool, this eliminates an Flamerobin problem, correct?

**Comment by jrcarlsen** [comment]
I am no longer with the company that had this problem, so I will not be able to do any further testing.

**Comment by mariuz** [comment]
seems to be firebird related issue , not flamerobin , I will close it for now
