### ISSUE TITLE
Change version numbering to 4.0.20220627 (About box + file version too!)

### ISSUE THREAD

**Issue by PizzaProgram** [mariuz/flamerobin#262]
# 1.  
I would like to ask to stop this _meaningless_ `0.9.3.xyz` version numbering, because this program is:  
 - Production ready since a long time.  
 - Aiming to work with FB4 .  
 (That's why I recommend re-starting with `4.0.yyyymmdd` .... and later when all errors fixed related to FB4: `4.1.yyyymmdd`)  
 - The 3th part would allow to identify easier the release date in ISO standard format.  
  
# 2.
Also please change the About Box to:  
 - **Show the current version number.**   
 - Put a link to this site link instead of just "flamerobin.org". 
 - Write before "flamerobin.org" link this line: _"The old site is (not maintained since 20xx) : "_  

# 3.
If I right click the EXE file > it still shows `File version   0.9.3.0`  
So it is currently impossible to us to verify which version is installed.  
_(Was the installation succesfull? Did it properly overwrite the old exe?)_

# 4.
You may show this number on top of the program window too, beginning with a "v" letter:
 - "FlameRobin FirebirdSQL Admin (v4.0.20220627)"
Because it can only handle FirebirdSQL and no other "universal databases". Right?
So the name of the program should reflect that. 
_(To prevent if someone accidentally installing it and trying to use it for other purposes.)_

# Detailed explonation.  
If you are a pro-developer you must know how difficult is to remember:  
 - which version fixed which error  
 - or did set new library/OS/FB minimums  
  
_I myself can not remember well of my own program after a few years, so I have to search within release notes sometimes, while I'm **already USING dates** as version numbers since 20 years.  
So imagine how difficult is it for a simple user like us, working on multiple PCs, always downloading " `0.9.3` " and can not tell, if it's already handling FB4 Bool type or not?_

**Comment by mariuz** [comment]
After the snapshot become more stable we will release a 1.x version , 
i will update the site today with news about the latest snapshot version 

Snapshot is still a testing prerelease version , this is why we don't call it stable even if is in usable state :)

**Comment by krilbe** [comment]
Excellent idea!

Is it not possible also to resume work on the flamerobin.org site, or as 
an alternative: shut it down? Who owns it? If it's not being maintained 
I think it has no use and should be taken down. Move anything that's 
still relevant to GitHub or whatever?

Regards,
Kjell Rilbe

---------------------------------------------------------------------------
Kjell ***@***.***>
Telefon: 0733-44 24 64 (+46 733 442464)
---------------------------------------------------------------------------
"If there's a price for bein' me, that's one I'll have to pay"
Aaron Tippin
---------------------------------------------------------------------------

Den 2022-06-27 kl. 11:18, skrev PizzaProgram:
