### ISSUE TITLE
Font color is white in the tree on Windows Server 2008 and below

### ISSUE THREAD

**Issue by nLeonardt95** [mariuz/flamerobin#267]
Font color is white in the tree. (see screenshot)

The issue occurs with Windows Server 2008 R2.
From Windows Server 2012 and higher, the problem does not exist.

![image](https://user-images.githubusercontent.com/60505315/181439321-3ca26d58-260b-4edf-acdd-0ff5c9bcc621.png)

**Comment by Jdochoa** [comment]
What version of FR are you using?

**Comment by nLeonardt95** [comment]
> 

0.9.3.12 Snapshot Pre-release
@[arvanus](https://github.com/arvanus) arvanus released this 26 Jun 2022

**Comment by elzner2** [comment]
problem still exists in 0.9.7
![image](https://github.com/mariuz/flamerobin/assets/7190458/ade619b3-f7c4-4eda-8925-33ed9975f344)

color in sql window dropdown is not right either:
![image](https://github.com/mariuz/flamerobin/assets/7190458/35de8a9e-9bd7-4589-87c0-21d3ee2f5095)

**Comment by mariuz** [comment]
https://learn.microsoft.com/en-us/troubleshoot/windows-server/windows-server-eos-faq/end-of-support-windows-server-2008-2008r2
