### ISSUE TITLE
About Firebird database link

### ISSUE THREAD

**Issue by wudai8** [mariuz/flamerobin#268]
我在使用FlameRobin工具连接Firebird数据时，出现错误，你能帮下我吗？ @mariuz

**Comment by wudai8** [comment]
I made an error when using the flamerobin tool to connect Firebird data. Can you help me?

**Comment by wudai8** [comment]
![84b757df2a538cbeae08b2bdd6c1a2e](https://user-images.githubusercontent.com/105644366/181591553-aefc8a19-c68e-4aa4-babe-e2b7fabaa847.jpg)

**Comment by Jdochoa** [comment]
Please give me more information about the version of FB and FR you are using.

./jo

**Comment by mariuz** [comment]
Seems to be a Firebird user/password configuration issue , please verify if you can connect with isql from command line 

https://stackoverflow.com/questions/4272399/firebird-error-username-and-password-are-not-defined-with-delphi-application
