### ISSUE TITLE
unhandled error in FlameRobin (OSX 10.13.6)

### ISSUE THREAD

**Issue by awunnenb** [mariuz/flamerobin#27]
FlameRobin: 0.9.3 
from 2013 :-(
Mac OSX: 10.13.6

Template /Applications/FlameRobin.App/Contents/SharedSupport/sys-templates/browse-data.template not found

**Comment by Tomas2D** [comment]
Hello Andreas!
Maybe this tutorial that I have sent to @mariuz will help you.

[http://flamerobin.blogspot.com/2016/01/compiling-flamerobin-under-mac-os-x.html](http://flamerobin.blogspot.com/2016/01/compiling-flamerobin-under-mac-os-x.html)

> - You have to manually copy sys-template folder (from downloaded Flamerobin folder) to your > Application content folder.
>  For example:  "/Applications/FlameRobin.app/Contents/SharedSupport/sys-templates)"

**Comment by arvanus** [comment]
Hi, can I close this issue?
Thanks

**Comment by awunnenb** [comment]
Yes
