### ISSUE TITLE
Dependencies do not show dependency on function

### ISSUE THREAD

**Issue by livius2** [mariuz/flamerobin#281]
Hi

when you go to function e.g. udf and look at function dependencies  you see e.g. that some procedure use it.
But when you go to that procedure and you look at dependencies there are no dependency on that function.

It will be helpful, as if someone need to remove external function and replace it with built in it is much harder to do this in one pass.
E.g. in procedure there are 3 used functions. And you replace only one, as you see dependency only from function side.

**Comment by ron90** [comment]
**FlameRobin 0.9.10** 

There is a same problem with stored functions also. Stored functions are not shown in the list when viewing dependencies of a table.

**Comment by arvanus** [comment]
Please, try next snapshot
