### ISSUE TITLE
fr_databases.conf is storing passwords in plain text

### ISSUE THREAD

**Issue by willibrandon** [mariuz/flamerobin#29]
fr_databases.conf is storing passwords in plain text when the Authentication option **Used saved user name and password** is used. I understand that if a machine is compromised and this authentication option is currently being used, that an attacker would be able to gain access to the database anyways. However, it is bad practice to store passwords in plain text.

**Comment by mariuz** [comment]
you can use the encryption this way https://photos.app.goo.gl/sEG9Zp8GP1ahpW1d8
