### ISSUE TITLE
Problems at new Style configuration

### ISSUE THREAD

**Issue by arvanus** [mariuz/flamerobin#292]
@Jdochoa could you take a look at the new style? 
I got 2 minor issues from now, when I try to type a SQL, it always changes the keywords to `mixed case`, in the default behavior of flamerobin is to use uppercase for keywords, BUT I cant change the casing even when I retype the word, example "FROM", "FrOm", "fROm" always shows as "From"
![image](https://user-images.githubusercontent.com/8182958/207949036-e2fad66e-a470-4242-8d06-25c07b9bb674.png)

Also, I opened the `Style Configurator`, scrolled a bit, saved, closed, reopened and got this error:
![image](https://user-images.githubusercontent.com/8182958/207949244-c804b69c-afc8-45b7-8633-b0a65ae58eba.png)

Thank you

**Comment by Jdochoa** [comment]
Hello @arvanus 

The first thing is changed in: Style Configurator\SQL\KEYWORD\Font Case.

The second problem is because a style has not been selected.

See the image below

![292](https://user-images.githubusercontent.com/11672188/207963026-8292e339-c422-419f-8d0b-c48ae61c5a32.png)

**Comment by arvanus** [comment]
It worked, looks like I needed to reopen Fr to refresh style config
Thank you! nice feature!

**Comment by luronumen** [comment]
Hi @arvanus 

I am still facing the same issue even after installing it thru the new [flamerobin-0.9.6-setup-x64.exe](https://github.com/mariuz/flamerobin/releases/download/0.9.6/flamerobin-0.9.6-setup-x64.exe) installer.
Is there any way for fixing it in manually?

Thanks in advanced,
Luciano

**Comment by andreschulle** [comment]
I am having the same problem @arvanus had. The font was blank, so I selected a font and saved, then an error said the access was denied. When executing Flame Robin as administrador, there's no error message, but preferences isn't saved. 

> It worked, looks like I needed to reopen Fr to refresh style config Thank you! nice feature!

I reopened the app, but the font field still appears blank.

**Comment by virgoparna** [comment]
Saving changes is not possible even after selecting style, because it tries to save to install location (%ProgramFiles%\Flamerobin\xml-styles\stylers.xml). i think that user changes should be saved somewhere at %appdata%\Flamerobin or %LocalAppData%\Flamerobin

**Comment by virgoparna** [comment]
Seems to be fixed by 0.9.9 snapshot (be8c3444). Probably by #330 pull request.
