### ISSUE TITLE
Fatal Error when selecting the "Browser data" option from a table

### ISSUE THREAD

**Issue by luronumen** [mariuz/flamerobin#294]
**Actual Result**
- Fatal Error when selecting the "Browser data" option from a table

![FlameRobinIssue](https://user-images.githubusercontent.com/8019466/208647309-392bcf69-8926-4bde-9414-43d2a6e45a3b.png)

**Expected Result**
-  FlameRobin 0.9.6 should display the table data when selecting the "Browser data" option from a table

**Steps to Reproduce the Issue**
- Open a Database and right click a table selecting the "Browser data" option.

**Comment by luronumen** [comment]
When the user selects the Yes option in the dialog in the previous image the following error dialog is displayed:

![Untitled](https://user-images.githubusercontent.com/8019466/208648863-589b6cda-d4f6-4497-b64f-52d176e00d29.png)

**Comment by ron90** [comment]
Actually the problem is with the setup installer. I faced the same errors in FlameRobin 0.9.6.
You can see the discussion and manual solution at #293

**Comment by arvanus** [comment]
Please, download and install the latest release file again
Should be fixed now

**Comment by luronumen** [comment]
This issue is no longer reproducible on [flamerobin-0.9.6-setup-x64.exe](https://github.com/mariuz/flamerobin/releases/download/0.9.6/flamerobin-0.9.6-setup-x64.exe).

Thanks for the fix!

Best Regards,
Luciano
