### ISSUE TITLE
Error loading fbclient.dll which is not a valid Win32 app

### ISSUE THREAD

**Issue by pgfiore** [mariuz/flamerobin#295]
Hi there, I hope everything is going well with you.
I've just installed latest snapshot flamerobin-0.9.6-setup-x64 on a working 0.9.3.1bd8c1ac-setup-x64 (it's a WinServer 2019).
The tool now fires an error while loading the win32 version of the fbclient.dll.
Firebird is a plain installation: Firebird-2.5.9.27139_0_x64. And the C:\Program Files\Firebird\Firebird_2_5\WOW64\fbclient.dll is the original one and certainly a "win32" file too (as shown by the below image).
![image](https://user-images.githubusercontent.com/25175532/208858375-2f42361c-0009-4368-ac16-fc9cdf64ec3e.png)
Could you kindly help?
Ciao

**Comment by Jdochoa** [comment]
@pgfiore  Try FBCliente for x64

**Comment by pgfiore** [comment]
Thank you Jdochoa. I've overwritten the WOW64\FBClient.dll with the bin\FBClient.dll and it works like a charm.
Do you mind if I ask why my x64  installation is looking in the WOW64 folder (which is the win32 one)?

**Comment by Jdochoa** [comment]
Hello @pgfiore 
I'm not sure, but the windows look there.

./jo

**Comment by pgfiore** [comment]
I'm not able to sort it out, but IMHO opinion, it sounds a bit weird.
The error msg states that "it isn't a win32 app", but it's undoubtedly fake. The original FBClient on the WOW64 folder has proven to be a Win32 lib.
The Flamerobin installation was done using the flamerobin-0.9.6-setup-x64, which should look for and load from x64 libs only.
Furthermore, despite the name, the Windows on Windows (WOW64) folders are designated to file win32 libraries (it has something to do with the legacy "system32" name inherited from the old days).

In the end, it seems that x64 Flamerobin thinks of being an x32 app (and loading DLLs consequently)...
