### ISSUE TITLE
flamerobin is not working offline 

### ISSUE THREAD

**Issue by codz01** [mariuz/flamerobin#298]
Hi
if i am connected to the internet flamerobin works without problem but if i am offline it shows this error message when i tried create new database 
![flamerobin](https://user-images.githubusercontent.com/10813427/210498697-f97dc4c2-69df-46cd-b840-98a1248ee57a.jpg)

i am on windows7 32bits , firebird 3 , latest flamerobin

**Comment by arvanus** [comment]
Looks like some Windows problem
Try to use `127.0.0.1` instead of localhost

**Comment by codz01** [comment]
thanks , it works after using 127.0.0.1
