### ISSUE TITLE
Error opening Preferences and Creating new objects

### ISSUE THREAD

**Issue by kbhoward** [mariuz/flamerobin#302]
FlameRobin 9.6
Debian 12 GNU/Linux 64bit

Opening preferences causes an error, missing XML file.
Same missing file causes FlameRobin to error and immediately close when trying to create a new domain or new exception.  This was a fresh install of FlameRobin.
![Screenshot at 2023-02-18 00-22-31](https://user-images.githubusercontent.com/8135585/219843266-2f452200-c30d-4385-a8e5-6325088d769a.png)

**Comment by mariuz** [comment]
for the moment copy them manually there from xml-styles folder

https://github.com/mariuz/flamerobin/tree/master/xml-styles

**Comment by mariuz** [comment]
@kbhoward See the related discussion 

https://github.com/mariuz/flamerobin/discussions/293

**Comment by kbhoward** [comment]
Gotcha.  I already copied one of the themes and simply renamed it .xml.
thanks for the response, and if there is anything I can do to help, please
let me know.  Not much of a developer, tho...

**Comment by Kyogre** [comment]
So for a workaround we can use one of two ways:
1. just rename any one of the themes (e.g. `Mono Industrial.xml`) to `.xml` (yeah, very strange name for the file)
2. open Preferences > SQL Editor > Style Configurator > select any theme from the list > Save
