### ISSUE TITLE
Double EXECUTE IN DDL's Procedure 

### ISSUE THREAD

**Issue by Jhironsel** [mariuz/flamerobin#305]
![Captura de pantalla de 2023-03-20 12-44-45](https://user-images.githubusercontent.com/28508219/226411183-542388e7-e9bb-4f34-b8b1-4c9875b71975.png)
![Captura de pantalla de 2023-03-20 12-50-14](https://user-images.githubusercontent.com/28508219/226411290-417054ed-fb1e-4b1b-88cb-8d7caaedecc6.png)

**Comment by arvanus** [comment]
duplicates #40

**Comment by arvanus** [comment]
Hello, please try the artifact and see if it solves your problem
https://github.com/arvanus/flamerobin/actions/runs/6634275162

**Comment by Jhironsel** [comment]
It is OK... it Was Fixed, laster version.
