### ISSUE TITLE
Access denied when saving preferences 

### ISSUE THREAD

**Issue by arvanus** [mariuz/flamerobin#314]
![image](https://github.com/mariuz/flamerobin/assets/8182958/3e5dba4c-5310-4339-9eba-7ab09b40f790)
Related to new style configuration 
Steps to reproduce: simply open View->Preferences, and save 
Looks like this error doesn't interfere in the save process

**Comment by andreschulle** [comment]
Same problem here.

**Comment by isfce** [comment]
Try in administrator mode.

**Comment by andreschulle** [comment]
Tried it already. No error message is shown, but the preferences are not saved. When exiting the preferences window and then re-entering, it's like I haven't done any change.
