### ISSUE TITLE
Error editing a value in a float column

### ISSUE THREAD

**Issue by GenuineTom** [mariuz/flamerobin#316]
Editing a float column results in an error '-413 Overflow occurred during data type conversion'. In the UPDATE statement, it is shown that the float column is wrongly assigned to a string with a localized decimal separator (val_float='1,000000').
![flamerobin](https://github.com/mariuz/flamerobin/assets/135315716/1bf8b78f-6905-466f-a21e-90e12fd45d00)

**Comment by arvanus** [comment]
Hello, what version of FR are you using?
Also, please try to uncheck this option and see what happens
![image](https://github.com/mariuz/flamerobin/assets/8182958/f9a8b812-f0ac-45cb-8f39-ca9e69da6a4a)
