### ISSUE TITLE
MacOs arm64 library not found for -lfbclient

### ISSUE THREAD

**Issue by Nico-VL** [mariuz/flamerobin#317]
I'm new to develop apps on MacOs, so this may be a stupid question.
I'm trying to compile flamerobin 0.9.7 on a Mac, but got stuck with finding the right lib and where to place it.
I'm using firebird 4.0.1-2709-ARM64.pkg, and tried using the libfbclient.dylib, libfbclient.so, libfbclient.so.2.
I noticed their is also an extension .a but I couldn't find a file libfbclient.a.
ps: I can confirm that libfbclient.dylib is build for arm64

**Comment by arvanus** [comment]
If this works, can u do a pull request later as soon as user confirms fix?
Thanks!

**Comment by arvanus** [comment]
Closing as #328 looks like fixes this
