### ISSUE TITLE
can't open file

### ISSUE THREAD

**Issue by stkim2** [mariuz/flamerobin#325]
windows-32 

Localhost -> Create New Database  -> Connect (success)-> Tables -> Create New (error occurred)

C:\Program Files (x86)\FlameRobin\xml-styles\.xml  (error 2 : The specified file cannot be found.)

![캡처](https://github.com/mariuz/flamerobin/assets/74221015/82a395c3-68e8-42b8-a238-f5a36fa0bd8c)
![캡처1](https://github.com/mariuz/flamerobin/assets/74221015/55792a48-efa5-447d-81dc-af86b361e04f)

**Comment by stkim2** [comment]
Install Program
- Firebird-4.0.3.2975-0-Win32 
- flamerobin-0.9.7.0b8fef14-setup

System
OS : Windows 10 pro Ver.(22H2)
RAM : 32GB
Login account : administrator

**Comment by arvanus** [comment]
Just choose any theme under view>preference menu and save

**Comment by stkim2** [comment]
Thank you
Even though I did that, the same error occurs.

**Comment by arvanus** [comment]
Hi, please try the version from this issue: https://github.com/mariuz/flamerobin/issues/327

**Comment by arvanus** [comment]
hi, try latest snapshot.
If no reply I'll close this issue as solved
