### ISSUE TITLE
Cannot create a new FB database; fb_vrsion=2.5.8

### ISSUE THREAD

**Issue by thesunlover** [mariuz/flamerobin#33]
OS: Windows Server 2012 R2

![image](https://user-images.githubusercontent.com/6734600/56363224-62434100-61f4-11e9-87bd-8e2af9937378.png)
![image](https://user-images.githubusercontent.com/6734600/56363366-b8b07f80-61f4-11e9-80b6-0f93403c2935.png)

**Comment by arvanus** [comment]
Hellow @thesunlover, have you tried again this? And with other tools? 
Is firewall OK? Can you "telnet" do port 3050?
Thanks!

**Comment by mariuz** [comment]
seems to be a connection issue , not related to flamerobin
