### ISSUE TITLE
Update to Inno Setup 6

### ISSUE THREAD

**Issue by arvanus** [mariuz/flamerobin#333]
Run ISCC.exe install\win32\FlameRobinSetup.iss
Inno Setup 6 Command-Line Compiler
Copyright (C) 1997-2023 Jordan Russell. All rights reserved.
Portions Copyright (C) 2000-2023 Martijn Laan. All rights reserved.
Portions Copyright (C) 2001-2004 Alex Yackimoff. All rights reserved.
https://www.innosetup.com/

Compiler engine version: Inno Setup 6.2.2

Preprocessing
   Reading file: c:\program files (x86)\inno setup 6\ISPPBuiltins.iss
   Line 25: Including file: D:\a\FlamerobinActionTests\FlamerobinActionTests\src\frversion.h
   Reading file: D:\a\FlamerobinActionTests\FlamerobinActionTests\src\frversion.h
   Line 6 of frversion.h: Including file: D:\a\FlamerobinActionTests\FlamerobinActionTests\src\revisioninfo.h
   Reading file: D:\a\FlamerobinActionTests\FlamerobinActionTests\src\revisioninfo.h
Error on line 59 in D:\a\FlamerobinActionTests\FlamerobinActionTests\install\win32\FlameRobinSetup.iss: Minimum NT version specified by MinVersion must be at least 6.0. (Windows 2000/XP/Server 2003 are no longer supported.)
Compile aborted.
Parsing [Setup] section, line 39
Parsing [Setup] section, line 40
Parsing [Setup] section, line 42
Parsing [Setup] section, line 43
Parsing [Setup] section, line 44
Parsing [Setup] section, line 45
Parsing [Setup] section, line 50
Parsing [Setup] section, line 51
Parsing [Setup] section, line 53
Parsing [Setup] section, line 54
Parsing [Setup] section, line 58
Parsing [Setup] section, line 59
Error: Process completed with exit code 1.

**Comment by mariuz** [comment]
You can update MinVersion to 6

I see that Firebird installer require the same min version

**Comment by mariuz** [comment]
@arvanus this should be fixed now switched from 5.0 to 6.0 

https://github.com/mariuz/flamerobin/commit/8145cf0ae8eb6f491f9b2d11d74ce484c1dc8f46

Firebird install has more defines , but we don't need that complexity for the moment https://github.com/FirebirdSQL/firebird/blob/8e458c7bd0894e042fa5157c648bc45598485345/builds/install/arch-specific/win32/FirebirdInstall.iss#L144

**Comment by arvanus** [comment]
Hi, thank you
I'm improving GitHub actions in a parallel project, my goal is to automatically build snapshots for windows
I just don't know how to upload the snapshot yet.

**Comment by arvanus** [comment]
https://github.com/arvanus/FlamerobinActionTests/actions/runs/6518829659/job/17704669117
