### ISSUE TITLE
Triggers comments are not shown

### ISSUE THREAD

**Issue by Romualdo-Caruso** [mariuz/flamerobin#339]
When inspecting triggers of a table, either going to "Triggers" menu or to "Table / Triggers" menu, their comments are not shown.

**Comment by arvanus** [comment]
Please, try the installer from the artifact from here: (will be ready in some minutes) 
https://github.com/mariuz/flamerobin/actions/runs/6551576355

**Comment by Romualdo-Caruso** [comment]
Thanks !
