### ISSUE TITLE
Error trying to build on Windows

### ISSUE THREAD

**Issue by arvanus** [mariuz/flamerobin#35]
Hi, I´m following this link http://flamerobin.blogspot.com/2015/11/flamerobin-building-instructions-for.html
to build using VS2015 (I was using Mingw previuslly) 
Everything goes fine while building boost-1.62.0 and wxWidgets-3.1.3
But when I try to build Flamerobin from cmd:
```
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat"
set WXDIR=D:\wxWidgets-3.1.3
set WXWIN=D:\wxWidgets-3.1.3
set BOOST_ROOT=D:\\boost_1_62_0
set BOOST_LIB_DIR=D:\boost_1_62_0\stage\lib
cd flamerobinRepoDir
nmake -f makefile.vc FINAL=0 USEDLL=0


```

 I get this error:

> Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> update-revision-info.cmd
> cl /c /nologo /TP /Fovcud\flamerobin_frprec.obj /MDd /DWIN32 /Zi  /D_DEBUG /Fdvcud\flamerobin.pdb  /Od /W4 /D__WXDEBUG__ /D_DEBUG  /D_WINDOWS /D__WINDOWS__ /DWINVER=0x400 /DWIN32 /D__WIN32__ /D__WIN95__  /DSTRICT /D__WXMSW__ /DwxUSE_GUI=1 /DwxUSE_REGEX=1 /DwxUSE_UNICODE=1  /DWIN32_LEAN_AND_MEAN  /ID:\wxWidgets-3.1.3\lib\vc_lib\mswud  /ID:\wxWidgets-3.1.3\contrib\include /ID:\wxWidgets-3.1.3\include /ID:\boost_1_62_0 /D_WINDOWS  /DIBPP_WINDOWS /I. /I.\src /I.\src\ibpp /I.\res /GR /EHsc /Yu"wx/wxprec.h"  /Fp"vcud\flamerobin.pch"    /Ycwx/wxprec.h .\src\frprec.cpp
> frprec.cpp
> D:\wxWidgets-3.1.3\include\wx/msw/private.h(1062): error C2065: 'WS_EX_LAYOUTRTL': undeclared identifier
> NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"' : return code '0x2'
> Stop.

Googling for a response, I just got to this link https://forums.wxwidgets.org/viewtopic.php?t=42050
that suggests do specifying WINVER=0X0500 in the "Preprocessor Definitions" section. but got the same error

Can someone give a idea of what to do?
Thanks

**Comment by arvanus** [comment]
Fixed, for future use:

1.  At Configuration Properties>C/C++>Preprocessor:

- Add "WINVER=0x500" to Preprocessor Definitions

2. At Configuration Properties>C/C++>Code Generation:
 - Change Runtime Library to the same as at used at wxWidget (easier fix)
- -in my case was: Multi-threaded Debug DLL (/MDd)

And, in Linker>Input:
- change wxmsw30* to wxmsw31*
- change wxbase30* to wxbase31*

And, lastly (but first), I build boost in this way:
```
cd \boost_1_62_0\
cd tools\build\src\engine\
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
rem I really dont remember why I specified thread, datetime system and asio, but wharever, it worked 😄 
build.bat vc14 link=static --with-thread --with-date_time --with-system --with-asio

cd \boost_1_62_0\
bjam toolset=msvc-14.0

```

**Comment by NoeVG** [comment]
Hi, easy only rename files remove the char 'u' in the files in lib

**Comment by NoeVG** [comment]
HI, ha ha ha another option it's set flag in compile source:

nmake /f makefile.vc BUILD=release UNICODE=0
