### ISSUE TITLE
COMMENT ON PARAMETER

### ISSUE THREAD

**Issue by Jhironsel** [mariuz/flamerobin#353]
Missing name's procedures. 
![Captura desde 2023-11-15 11-36-52](https://github.com/mariuz/flamerobin/assets/28508219/ca510c19-47e6-4f25-8ba5-3bcdb55d1a0c)

Now Name. 
![Captura desde 2023-11-15 11-38-49](https://github.com/mariuz/flamerobin/assets/28508219/080ffdab-b7a3-4049-9f63-ad22ef3d9fa6)

**Comment by arvanus** [comment]
OK, I'll take a look
