### ISSUE TITLE
Current Build/Make instructions for Linux

### ISSUE THREAD

**Issue by DaltonCalford** [mariuz/flamerobin#359]
I was looking over the codebase and I have not seen any instructions for building on Linux.

I was able to get a build compiled after fiddling with wxtools but, it is still failing on dealing with timezone fields and displaying binary(16) fields as uuids

Is there an updated build process for Linux or any linux snapshots?

**Comment by mariuz** [comment]
https://github.com/mariuz/flamerobin/wiki/How-to-Build-flamerobin-on-ubuntu-or-debian
