### ISSUE TITLE
Data Type Unknown in RDB$BACKUP_HISTORY 

### ISSUE THREAD

**Issue by Jhironsel** [mariuz/flamerobin#360]
![Captura desde 2023-12-13 20-18-20](https://github.com/mariuz/flamerobin/assets/28508219/91cd9eaf-d66d-47b3-8135-6e339ed5d3d5)

Field RDB$TIMESTAMP

**Comment by arvanus** [comment]
Hi
Are you using latest Flamerobin version and Fb4.0+ fbclient.dll?

**Comment by Jhironsel** [comment]
Debian 12
libfbclient.so.4.0.4
FlameRobin 0.9.10 (git hash f4386f82) Unicode

**Comment by Jhironsel** [comment]
It seems to be resolved in a clean environment.

**Comment by Jhironsel** [comment]
![Captura desde 2024-01-13 16-17-17](https://github.com/mariuz/flamerobin/assets/28508219/991713a0-e0ed-4184-bc76-04c2a5958d21)
