### ISSUE TITLE
Bug, when I need to see the property of a field.

### ISSUE THREAD

**Issue by Jhironsel** [mariuz/flamerobin#365]
This happens to me when I go to view the property of a primary key.
![Captura desde 2024-01-09 08-25-04](https://github.com/mariuz/flamerobin/assets/28508219/7942958d-46a5-4783-a789-a72af905ac8f)

This doesn't happen when I query a field like varchar.
![Captura desde 2024-01-09 08-26-13](https://github.com/mariuz/flamerobin/assets/28508219/68418233-d46d-4c27-93c6-fe32bd925c13)

Also occurs in a boolean field.
![Captura desde 2024-01-09 08-32-48](https://github.com/mariuz/flamerobin/assets/28508219/8a3bb5e8-8050-4736-abd8-276d11dc6e1e)

Also occurs in a Date field.
![image](https://github.com/mariuz/flamerobin/assets/28508219/5f41f56f-4f2c-4e93-84d3-48f2deace562)

It doesn't happen in Blob fields.

It also happened in the previous version. And in this version of firebird too.
![Captura desde 2024-01-09 08-34-12](https://github.com/mariuz/flamerobin/assets/28508219/dd3fe827-d69e-4c8c-a102-067c28818ecf)

Debian 12.

How can I see the app's bug tracking?

**Comment by Jhironsel** [comment]
![Captura desde 2024-01-13 16-20-07](https://github.com/mariuz/flamerobin/assets/28508219/c6461da8-3839-44df-82d7-d20691bb0c3d)

It continues to break down in a clean environment.

Data types INTEGER, BIGINT, BOOLEAN among others.

Only with VARCHAR can the properties of the fields be displayed.

**Comment by Jhironsel** [comment]
Employee DB... Same Problem. 

![Captura desde 2024-01-13 17-11-15](https://github.com/mariuz/flamerobin/assets/28508219/83826bce-6704-4b13-9e6a-6c8fc64a2641)

**Comment by Jhironsel** [comment]
Working in Debian's repository.
Version 0.9.6 Unicode

![Captura desde 2024-01-14 01-08-26](https://github.com/mariuz/flamerobin/assets/28508219/2717e225-3888-4f53-bc0a-ccf1a9d82db5)

**Comment by livius2** [comment]
On Windows same problem with any `BIGINT` field. Doble clicking on it cause an fatal error:

![image](https://github.com/mariuz/flamerobin/assets/14888294/36e6e55d-f505-4ee7-bf71-b64b3a8406e8)

![image](https://github.com/mariuz/flamerobin/assets/14888294/0d2edf78-a7dc-46ca-8a77-c0304e993434)

if i remember correctly i had 9.0.8 previously and all was ok, so some recent change brake this.

**Comment by arvanus** [comment]
Please, try to use latest snapshot (you can download Windows build from latest action currently building) 
If it's working now, close this issue
