### ISSUE TITLE
Source code issue in src/sql/SqlStatement.cpp

### ISSUE THREAD

**Issue by hhfiddelke** [mariuz/flamerobin#372]
Flamerobin 0.9.10:

in file src/sql/SqlStatement.cpp Lines 502 and 507 ToInt() is used. 

wxString does not have a method ToInt()

**Comment by arvanus** [comment]
They exists for at least 2 years, from wxWidget 3.1.6
https://github.com/wxWidgets/wxWidgets/commit/9dc7248b1d745ca1a47c4006081311f4553114f4
https://github.com/wxWidgets/wxWidgets/blame/2dbe596bade85239dbc890a4bbcde3a3a4418fc5/include/wx/string.h#L2384-L2389

Also, Flamerobin is aiming to use wxWidget 3.2
https://github.com/mariuz/flamerobin/discussions/277
