### ISSUE TITLE
Suggestion. 

### ISSUE THREAD

**Issue by Jhironsel** [mariuz/flamerobin#376]
How could I remove the bold in the objects?

Could you add a button that allows you to reset them without having to disconnect?

![Captura desde 2024-03-22 15-49-56](https://github.com/mariuz/flamerobin/assets/28508219/45093268-5ec2-462e-b742-f40e4e59bc9b)

**Comment by arvanus** [comment]
Not possible currently, as the bold object is a visual representation of an object with the metadata loaded
But if you really want to completely remove the bold visual option, you can create a fork, and edit `src/gui/controls/DBHTreeControl.cpp`, changing every line with `nodeTextBoldM = true;` to `nodeTextBoldM = false;`
If you change in your repo in the main branch github Action will build the setup for you :) 

Also, you can do an better work and create a configurable option to enable/disable this visual hint, and pull a merge request for us 👍

**Comment by Jhironsel** [comment]
Ok
