### ISSUE TITLE
Capability to connect with multiple versions from same executable

### ISSUE THREAD

**Issue by mobius1qwe** [mariuz/flamerobin#389]
Currently flamerobin requires fbclient.dll on a specific version on the default folders. It would be an improvement to be able to add a new field to set the .dll to connect with that specific server.

As shown on the image below, add a field below the 3 existing ones to point the location of the .dll to connect on the server
![image](https://github.com/user-attachments/assets/4ccc2335-6e38-4149-b232-5fdd9b2fbb8e)

**Comment by arvanus** [comment]
Unfortunately, IBPP doesn't support per connection dll, so it's not possible unless someone make a path for IBPP first
