### ISSUE TITLE
Fatal error when trying to edit a time field of a record

### ISSUE THREAD

**Issue by luronumen** [mariuz/flamerobin#398]
**Actual Result**
- Fatal error when trying to edit a time field of a record.

![FatalError](https://github.com/user-attachments/assets/b085cfc4-50fb-41a0-9b30-da4c13795a38)

**Expected Result**
- The user should be able to edit any field in a record.

**Steps to Reproduce The Issue**
1. Right-click on a table that contains a Time field and select the _Browser Data_ option;
2. On the data screen, edit the time field of a record and press enter: Fatal error occurs!

**Environment Setup**
- Windows 11 version 23H2;
- FirebirdSQL 5.0.1 (x64);
- [FlameRobin 0.9.12 (x64)](https://github.com/mariuz/flamerobin/releases/download/0.9.12/flamerobin-0.9.12-setup-x64.exe)

**Comment by arvanus** [comment]
Related with
https://github.com/mariuz/flamerobin/pull/362

**Comment by arvanus** [comment]
please, try latest build. Download from here:
https://github.com/mariuz/flamerobin/actions/runs/11543674818
if it works, I'll release another snapshot today

**Comment by luronumen** [comment]
This issue is no longer reproducible on https://github.com/mariuz/flamerobin/actions/runs/11543674818
Thank you very much for the fix @arvanus
