### ISSUE TITLE
Lots of assert errors

### ISSUE THREAD

**Issue by arvanus** [mariuz/flamerobin#42]
Example: when you go to Privileges tab of a table, and click at "Grant and revoke privileges"
Error occurs at wxWidgets 3.1.3
![image](https://user-images.githubusercontent.com/8182958/85644200-afc70380-b66c-11ea-9e5a-95483a8d41fa.png)
(I know that I can disable  assert dialog, but I hasn't tried to do it yet)

**Comment by arvanus** [comment]
next error:
![image](https://user-images.githubusercontent.com/8182958/85644335-fae11680-b66c-11ea-9787-487f7407f933.png)

**Comment by arvanus** [comment]
Workaround:
edit wxWidgets-3.1.3\lib\vc_lib\mswu\wx\setup.h and add 
`#define wxDEBUG_LEVEL 0`
Rebuild wxWidget and Flamerobin

**Comment by luronumen** [comment]
Hi @arvanus,
 
Is this issue still reproducible in [0.9.3.8 Snapshot](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.8) version?

**Comment by arvanus** [comment]
Not that I had seen
Thanks for the help reviewing the issues :)
