### ISSUE TITLE
flamerobin_ExecuteSqlFrame.o: en la función `ExecuteSqlFrame::execute(wxString, wxString const&, bool)':

### ISSUE THREAD

**Issue by Jhironsel** [mariuz/flamerobin#43]
g++ -o flamerobin flamerobin_addconstrainthandler.o flamerobin_Config.o flamerobin_DatabaseConfig.o flamerobin_ArtProvider.o flamerobin_CodeTemplateProcessor.o flamerobin_FRError.o flamerobin_Observer.o flamerobin_ProgressIndicator.o flamerobin_StringUtils.o flamerobin_Subject.o flamerobin_TemplateProcessor.o flamerobin_URIProcessor.o flamerobin_Visitor.o flamerobin_databasehandler.o flamerobin_MetadataLoader.o flamerobin_frprec.o flamerobin_frutils.o flamerobin_AboutBox.o flamerobin_AdvancedMessageDialog.o flamerobin_AdvancedSearchFrame.o flamerobin_BackupFrame.o flamerobin_BackupRestoreBaseFrame.o flamerobin_BaseDialog.o flamerobin_BaseFrame.o flamerobin_CommandManager.o flamerobin_ConfdefTemplateProcessor.o flamerobin_ContextMenuMetadataItemVisitor.o flamerobin_ControlUtils.o flamerobin_DataGrid.o flamerobin_DataGridRowBuffer.o flamerobin_DataGridRows.o flamerobin_DataGridTable.o flamerobin_DBHTreeControl.o flamerobin_DndTextControls.o flamerobin_LogTextControl.o flamerobin_PrintableHtmlWindow.o flamerobin_TextControl.o flamerobin_CreateIndexDialog.o flamerobin_DataGeneratorFrame.o flamerobin_DatabaseRegistrationDialog.o flamerobin_EditBlobDialog.o flamerobin_EventWatcherFrame.o flamerobin_ExecuteSqlFrame.o flamerobin_ExecuteSql.o flamerobin_FieldPropertiesDialog.o flamerobin_FindDialog.o flamerobin_FRLayoutConfig.o flamerobin_GUIURIHandlerHelper.o flamerobin_HtmlHeaderMetadataItemVisitor.o flamerobin_HtmlTemplateProcessor.o flamerobin_InsertDialog.o flamerobin_MainFrame.o flamerobin_MetadataItemPropertiesFrame.o flamerobin_MultilineEnterDialog.o flamerobin_PreferencesDialog.o flamerobin_PreferencesDialogSettings.o flamerobin_PrivilegesDialog.o flamerobin_ProgressDialog.o flamerobin_ReorderFieldsDialog.o flamerobin_RestoreFrame.o flamerobin_ServerRegistrationDialog.o flamerobin_SimpleHtmlFrame.o flamerobin_StatementHistoryDialog.o flamerobin_StyleGuide.o flamerobin_UserDialog.o flamerobin_UsernamePasswordDialog.o flamerobin_logger.o flamerobin_main.o flamerobin_MasterPassword.o flamerobin_column.o flamerobin_constraints.o flamerobin_CreateDDLVisitor.o flamerobin_database.o flamerobin_domain.o flamerobin_exception.o flamerobin_function.o flamerobin_generator.o flamerobin_Index.o flamerobin_metadataitem.o flamerobin_MetadataItemCreateStatementVisitor.o flamerobin_MetadataItemDescriptionVisitor.o flamerobin_MetadataItemURIHandlerHelper.o flamerobin_MetadataItemVisitor.o flamerobin_MetadataTemplateCmdHandler.o flamerobin_MetadataTemplateManager.o flamerobin_parameter.o flamerobin_privilege.o flamerobin_procedure.o flamerobin_relation.o flamerobin_role.o flamerobin_root.o flamerobin_server.o flamerobin_table.o flamerobin_trigger.o flamerobin_User.o flamerobin_view.o flamerobin_objectdescriptionhandler.o flamerobin_Identifier.o flamerobin_IncompleteStatement.o flamerobin_MultiStatement.o flamerobin_SelectStatement.o flamerobin_SqlStatement.o flamerobin_SqlTokenizer.o flamerobin_StatementBuilder.o flamerobin_statementHistory.o flamerobin_StyleGuideGTK.o  -L.     -L/usr/lib/x86_64-linux-gnu -pthread   -lwx_gtk3u_unofficial_aui-3.0 -lwx_gtk3u_unofficial_stc-3.0 -lwx_gtk3u_unofficial_xrc-3.0 -lwx_gtk3u_unofficial_webview-3.0 -lwx_gtk3u_unofficial_html-3.0 -lwx_gtk3u_unofficial_qa-3.0 -lwx_gtk3u_unofficial_adv-3.0 -lwx_gtk3u_unofficial_core-3.0 -lwx_baseu_unofficial_xml-3.0 -lwx_baseu_unofficial_net-3.0 -lwx_baseu_unofficial-3.0   -lboost_thread -lboost_system -pthread  -lboost_chrono  -libpp -lfbclient 
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find variable specification at offset 5fb7a
/usr/bin/ld: DWARF error: could not find variable specification at offset 5fbb1
/usr/bin/ld: DWARF error: could not find variable specification at offset 5fb6c
/usr/bin/ld: DWARF error: could not find variable specification at offset 5e788
/usr/bin/ld: DWARF error: could not find variable specification at offset 5e7bf
/usr/bin/ld: DWARF error: could not find variable specification at offset 5e77a
/usr/bin/ld: DWARF error: could not find variable specification at offset 605c6
/usr/bin/ld: DWARF error: could not find variable specification at offset 606b4
/usr/bin/ld: DWARF error: could not find variable specification at offset 607a2
/usr/bin/ld: DWARF error: could not find variable specification at offset 60890
/usr/bin/ld: DWARF error: could not find variable specification at offset 6097e
/usr/bin/ld: DWARF error: could not find variable specification at offset 60a6c
/usr/bin/ld: DWARF error: could not find variable specification at offset 60b5a
/usr/bin/ld: DWARF error: could not find variable specification at offset 60c48
/usr/bin/ld: DWARF error: could not find variable specification at offset 60d36
/usr/bin/ld: DWARF error: could not find variable specification at offset 60e24
/usr/bin/ld: DWARF error: could not find variable specification at offset 60f12
/usr/bin/ld: DWARF error: could not find variable specification at offset 61138
/usr/bin/ld: DWARF error: could not find variable specification at offset b314
/usr/bin/ld: DWARF error: could not find variable specification at offset b372
/usr/bin/ld: DWARF error: could not find variable specification at offset b3dc
/usr/bin/ld: DWARF error: could not find variable specification at offset 2ba92
/usr/bin/ld: DWARF error: could not find variable specification at offset 2ba9e
/usr/bin/ld: DWARF error: could not find variable specification at offset 2c0ad
/usr/bin/ld: DWARF error: could not find variable specification at offset 2c0f4
/usr/bin/ld: DWARF error: could not find variable specification at offset 2c13b
/usr/bin/ld: DWARF error: could not find variable specification at offset 2c732
/usr/bin/ld: DWARF error: could not find variable specification at offset 2c761
/usr/bin/ld: DWARF error: could not find variable specification at offset 2c79c
/usr/bin/ld: DWARF error: could not find variable specification at offset 2c7a8
/usr/bin/ld: DWARF error: could not find variable specification at offset 2c7e3
/usr/bin/ld: DWARF error: could not find variable specification at offset 2c7ef
flamerobin_ExecuteSqlFrame.o: en la función `ExecuteSqlFrame::execute(wxString, wxString const&, bool)':
/mnt/Almacen1TB/flamerobin-master/release/../src/gui/ExecuteSqlFrame.cpp:2398: referencia a `InsertParametersDialog::InsertParametersDialog(wxWindow*, IBPP::Ptr<IBPP::IStatement>&, Database*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, wxString, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, wxString> > >&)' sin definir
collect2: error: ld returned 1 exit status
make: *** [Makefile:271: flamerobin] Error 1

**Comment by arvanus** [comment]
Hello, can you please send me your steps?
I need to add InsertParametersDialog to makeFile, but as I use Windows I wasn't able to test accordingly in Linux  
Thanks

**Comment by arvanus** [comment]
Hi, please test the latest source available and let me know if it's working

**Comment by arvanus** [comment]
I believe it's working now
