### ISSUE TITLE
Does not Support new Firebird 3.X DataTypes

### ISSUE THREAD

**Issue by lhengen** [mariuz/flamerobin#44]
Does not support BIGINT and BOOLEAN data types (likely others).  Cannot display metadata properly, and cannot perform selects.  Essentially tool is now useless if using newer types.  Great tool, would love to see it updated.

**Comment by arvanus** [comment]
Hi, please test the latest snapshot available and let me know if it's working 
https://github.com/mariuz/flamerobin/releases/tag/0.9.3.2

**Comment by lhengen** [comment]
Works like a charm.  Viewing Table properties no longer throws an error.  Looking forward to a 64 bit release.
