### ISSUE TITLE
Underscore is wrongly shown in the Indices of the tables

### ISSUE THREAD

**Issue by luronumen** [mariuz/flamerobin#50]
Underscore is wrongly shown in the Indices of the tables

Current Version (0.9.3.55883844) = **FAIL**
![02 AR](https://user-images.githubusercontent.com/8019466/89841441-48e0a980-db49-11ea-86bb-38b8e3c991a2.png)

Previous Version (0.9.3.5ece15b) = **PASS**
![02 ER](https://user-images.githubusercontent.com/8019466/89841447-4aaa6d00-db49-11ea-98de-17f649ccd740.png)

**Comment by arvanus** [comment]
Thanks, I've just fixed it and pushed the patch do github
If you are urging to use the updated version, just copy `html-templates` folder to your install dir, or wait for the next snapshot (I'm thinking to build only when some other bigger bug is found)

**Comment by luronumen** [comment]
Hi @arvanus 

This issue is also reproducible on triggers summary tab. Could you please fix it? 

![03 AR](https://user-images.githubusercontent.com/8019466/89843697-daebb080-db4f-11ea-838c-19af78f8ffbe.png)

**Comment by arvanus** [comment]
I've found some other places too and hopefully fixed all

**Comment by luronumen** [comment]
Retest result on latest html-templates: **PASS**

Thank you very much for the fix @arvanus!
