### ISSUE TITLE
Unable to alter Database On Connect Trigger

### ISSUE THREAD

**Issue by luronumen** [mariuz/flamerobin#53]
According to the http://tracker.firebirdsql.org/browse/CORE-6234 
"In FB 3 the syntax of ALTER TRIGGER was changed to not allow to specify new type for DATABASE triggers."

For fixing this issue just remove the "ON CONNECT POSITION 0" line when alter a Database Trigger

![DatabaseTrigger](https://user-images.githubusercontent.com/8019466/89885720-df40b980-dba1-11ea-91de-b93eee19ef14.png)

**Comment by mariuz** [comment]
Seems that portable solution is : 

```
CREATE OR ALTER TRIGGER DATABASE_ON_CONNECT ACTIVE
ON CONNECT POSITION 0
AS
BEGIN
END
^
```

**Comment by luronumen** [comment]
Hi Popa,

You are completely right! Please follow the fix in your suggested way!

Best Regards,
Luciano

Em ter., 11 de ago. de 2020 às 07:53, Popa Marius Adrian <
notifications@github.com> escreveu:

**Comment by luronumen** [comment]
Hi *Popa*,

Is there any reason why the *new version 55883844** executable* is so big
compared to the *old version 5ece15b** executable*?

   - flamerobin.exe (old version 5ece15b) = *3,100 KB*
   - flamerobin.exe (new version 55883844) = *7,905 KB*

Is it being integrated into executable libraries unnecessary?
Should I open a bug for a better investigation on this?

Thank you very much for designing this tool that I consider the best
admin tool for Firebird!

Best Regards,
Luciano

Em ter., 11 de ago. de 2020 às 08:35, Luciano Rodrigues Nunes Mendes <
luronumen@gmail.com> escreveu:

**Comment by arvanus** [comment]
Hi @luronumen it was me who built the snapshot, so it's possible that I've lost an optimization step, no idea of which one could it be 😄

**Comment by luronumen** [comment]
That is fine @arvanus!
Thank you very much for your job for improving this tool!

**Comment by mariuz** [comment]
7,905 KB is tinny compared to games that i play these days (60G+)

Anyway we can optimize later for size , speed ...

**Comment by luronumen** [comment]
You're right Popa! Nobody believes how it is possible to make a Firebird
Admin as small and powerful as FlameRobin :)
Let's fix the issue https://github.com/mariuz/flamerobin/issues/47 first
and when we generate the next stable version we optimize as much as
possible (FlameRobin.exe around 3,100 KB).

Best Regards,
Luciano

Em ter., 11 de ago. de 2020 às 09:45, Popa Marius Adrian <
notifications@github.com> escreveu:
