### ISSUE TITLE
Add support for "PSQL Stored Functions" and "Packages"

### ISSUE THREAD

**Issue by luronumen** [mariuz/flamerobin#55]
Firebird 3.0 introduced 2 new concepts:
- PSQL Stored Functions (See:  https://firebirdsql.org/file/documentation/release_notes/html/en/3_0/rnfb30-psql-funcs.html)
- Packages (See: https://firebirdsql.org/file/documentation/release_notes/html/en/3_0/rnfb30-psql-packages.html)

Please Add support for "PSQL Stored Functions" and "Packages" by:
- Creating the *Packages* node;
- Ability for creating, altering, etc "PSQL Stored Functions" and "Packages"

**Comment by Jdochoa** [comment]
Hi @luronumen 
Can you give me feedback on this or close it? 
Thanks 

./jo

**Comment by luronumen** [comment]
For now we can close it!
