### ISSUE TITLE
Compatibility (<FB2.0) and Development (FlameRobin2)

### ISSUE THREAD

**Issue by PizzaProgram** [mariuz/flamerobin#59]
If the current version will **not** be able to handle old (< v2.0) databases correctly, than the whole program should be renamed and installed into a different directory with different name from now on! I suggest Simply:  
  **'FlameRobin2'**   
So users would at least have a chance to install both old and new version to the same system without interfering. ;-)

_This method would be also very practical for the **current** development! 
Because many of us, who use the prev. stable version daily, can simply **install the new next to the old** and compare..._ 

Please not forget about: `c:\Users\...\AppData\Local\flamerobin\`  too...
While installing the first time, it could run a simply 'import wizard" = copy script to get the :
`fr_settings.conf` + `fr_databases.conf` + `history` directory from the old one.
(_Because `code-templates` will be updated to new, since the old is buggy: can not insert BigSmallCase field names with "Quotes"._ )
... or, if it's easier: put a new menu under `Databases> Tools> Import from FlameRobin1` to do some simple file-copy.

(_IMHO we should not make the same mistake Firebird engine developers did when they have switched to FB3 and blocked the prev. versions to work with. Simply renaming the project would make it possible to coexist._ :-) )

**Comment by Jdochoa** [comment]
> 
> 
> @Jdochoa the changes you are doing will break compatibility with older versions?
> If yes then we will need to prepare the changes for "Flamerobin2" or something like that

@arvanus  I'm think we should keep backward compatibility with FB and FR.

**Comment by arvanus** [comment]
Yes, I think that too

**Comment by mariuz** [comment]
firebird  1.5 x is deprecated many years ago , who need old fr version they can create portable solutions / virtual machines  

https://firebirdsql.org/en/discontinued-versions/
