### ISSUE TITLE
Update the IBPP, wxWidgets and Boost libraries to the latest versions

### ISSUE THREAD

**Issue by luronumen** [mariuz/flamerobin#62]
- Update **IBPP** library to version **2.5.3.1** (https://sourceforge.net/projects/ibpp/files/ibpp/2.5.3/)
- Update **wxWidgets** library to version **3.1.4** (https://www.wxwidgets.org/)
- Update **Boost** library to Version **1.74.0** (https://www.boost.org/users/history/version_1_74_0.html)
- Update library versions on the FlameRobin **About** screen (Help > About)
- Update the Copyright to **2004-2020**

**Comment by mariuz** [comment]
IBPP is quite patched in flamerobin so current version is ok , wxwidgets/boost will be updated at a later time (no rush)

**Comment by luronumen** [comment]
Perfect @mariuz!

Best regards,
Luciano

**Comment by arvanus** [comment]
See #119 bug about wsWidget 3.1.4
Also, @blumf is working on remove Boost dependency, so FR will only depend on IBPP and wxWidget

**Comment by luronumen** [comment]
I saw bug #119 @arvanus!
Good to know that @blumf is working to remove the dependency on Boost. The less dependence on third parties we have, the better.

**Comment by Wolf-at-SO** [comment]
Do any of you know if there are plans to revive IBPP development here on Github?

**Comment by mariuz** [comment]
Feel free to extract :) In future we need to switch to Firebird 3 api
