### ISSUE TITLE
Question mark is missing from the dropping database dialog

### ISSUE THREAD

**Issue by luronumen** [mariuz/flamerobin#64]
**Question mark** is missing from the dropping database dialog:
- Please also delete the **cancel** button from this dialog:

Version 55883844 (Current version)
![55883844](https://user-images.githubusercontent.com/8019466/90401077-d3f2ff80-e073-11ea-9be9-5fb385004721.png)

Version 5ece15b (previous version)
![5ece15b](https://user-images.githubusercontent.com/8019466/90401104-dd7c6780-e073-11ea-8c57-610a513f49f2.png)

**Comment by arvanus** [comment]
I like the Cancel button, It's kind of "fool-proof".... in the doubt the user can always cancel 😸

**Comment by arvanus** [comment]
In fact I never dropped a database
This mesage is asked before or after dropping de database?

**Comment by luronumen** [comment]
- For the question in this dialog we can only have 2 possible answers: **Yes** or **No**.
- There is a previous dialog in which the user can cancel the Drop Database. Once the user clicks the Drop button, the database must be dropped:

![Drop](https://user-images.githubusercontent.com/8019466/90415751-eecf6f00-e087-11ea-86b3-6c9f6a646563.png)

**Comment by arvanus** [comment]
Ok, I get it, "Cancel" is really an bug in this case

**Comment by arvanus** [comment]
Apparently the "Question" icon is broken, the feature was kind of removed from wxWidget, you can read something more here:
https://forums.wxwidgets.org/viewtopic.php?t=45422
I ca put a nice "Asterisk" that looks like an Info icon 😄 
![image](https://user-images.githubusercontent.com/8182958/91100724-1308ee00-e63c-11ea-9a56-a7dd6ea7bb5a.png)

Also I tested this routine and it's behaving correctly when talking about de "Cancel" button, the database will only be deleted if you choose "Yes" or "No", if you click "Cancel" the whole operation is canceled

**Comment by luronumen** [comment]
Hi @arvanus 

The Cancel button on this screen has the same function as the cancel button on the previous screen: It does nothing!
If in the previous screen the user had already chosen to drop the database, the Cancel of this second screen should not prevent the database from being dropped.

For now, we can use an asterisk instead of the question mark on this screen :)

**Comment by arvanus** [comment]
Hi @luronumen 
I understand your concern about the redundant "Cancel" button, but as we are talking about dropping a Database I think that the ideal is to keep the actual behavior, after all, we can be talking about an in production database that the admin erroneously pressed Drop 2 times 😲, this second cancel can save the DBA a lot of troubles

You can take a look at the current code and what it does here:
https://github.com/mariuz/flamerobin/blob/235a8647a090c067528dd2ef572b903ff397392f/src/gui/MainFrame.cpp#L1557-L1574

If you are OK, I'll just fix the icon and close this issue, do you agree?

Thanks for your effort reporting and helping Flamerobin

**Comment by luronumen** [comment]
It's ok @arvanus .
Let's just fix the icon ;)
