### ISSUE TITLE
Random blank screen at connection

### ISSUE THREAD

**Issue by arvanus** [mariuz/flamerobin#65]
Randomly occurs:
![image](https://user-images.githubusercontent.com/8182958/90435866-0ddcf980-e0a6-11ea-92a0-c2a8150fa30e.png)
Expected behavior:
![image](https://user-images.githubusercontent.com/8182958/90436114-85ab2400-e0a6-11ea-81f5-51f37f97acb2.png)

Anyone got this problem too?
I don't know if it's a build problem, some cross-compile wxWidget error or another thing like that
@mariuz had you gotten this too?

**Comment by luronumen** [comment]
HI @arvanus 

This issue has happened to me several times but I was unable to identify a sequence of steps that was 100% reproducible.
This is an easier issue to be seen on high latency networks.
In other words, this is a valid issue and I hope you can find the root cause.

Best Regards,
Luciano

**Comment by arvanus** [comment]
I think it's something related to the thread while connecting, it's an easy stuff to mess with, and hard do find
😢
Unfortunately I have a little experience with threads in c++, and as it's not really and blocking bug, I won't try to fix it right now

**Comment by luronumen** [comment]
Hi @arvanus 

Did you have the opportunity to compare the current source code with the source code for version 5ece15b?
I am almost 100% sure that in version 5ece15b this issue would not happen.
Comparing the current code with the 5ece15b code can help you identify the issue.

**Comment by arvanus** [comment]
https://github.com/mariuz/flamerobin/compare/0.9.3.1...master
Looking across versions, I couldn't find much changes
I would list major changes: WINVER change from WINVER=0x400 to WINVER=0x500 and wxWidget change...
The change list aren't that long but off-course I could miss something

**Comment by luronumen** [comment]
If we don't have so many changes compared to the 5ece15b version, we are probably seeing this issue because the executable is not optimized.

Lets wait for the @mariuz reply in the issue #38 and retest this issue with the optimized version of flamerobin.

**Comment by arvanus** [comment]
I doubt that the lack of optimization is the cause. In fact to much optimization at compiler level can lead to some strange bugs like this small example:
https://developercommunity.visualstudio.com/content/problem/161765/c-compiler-bug-optimization-with-demo-code.html
But of course everything must be tested

**Comment by arvanus** [comment]
Looks like don't occurs at debug, just in the "Release Dynamic" build

**Comment by blumf** [comment]
Can we get a clear picture of what's happening?
 * Does the connection still open?
 * What method of opening is being used (e.g. double-click on registered DB)
 * What version of wxWidgets (check About dialog)

Looks to me like some kind of race condition in wx setting up the dialog. So I guessed at a possible solution in pull req #117

**Comment by arvanus** [comment]
> 
> 
> Can we get a clear picture of what's happening?
> 
>     * Does the connection still open?
> 
Yes
>     * What method of opening is being used (e.g. double-click on registered DB)
> 
double-click
>     * What version of wxWidgets (check About dialog)
> 
3.1.3
> 
> Looks to me like some kind of race condition in wx setting up the dialog. So I guessed at a possible solution in pull req #117
This bug just occurs randomly in release mode,when I'm running in debug mode never occurred
I'd guess it's related to some c++ optimization in release....

**Comment by blumf** [comment]
> > ```
> > * What version of wxWidgets (check About dialog)
> > ```
> 
> 3.1.3

Have you tried 3.1.4? Seeing as wx3.1 is the development branch, it's likely they've created some bugs along the way. Seen problems like this before in other desktop GUI libs (Qt, IUP), and it's usually a case of forcing the dialog to layout.

TBH I've just been using the wx debug DLLs for code work, I should really build the static libs.

**Comment by arvanus** [comment]
I'll try 3.1.4
I'll give a try to stable 3.0.5 too, (don't know if will compile)

**Comment by arvanus** [comment]
Apparently with the new cmake build it's working
