### ISSUE TITLE
Properties window not restored

### ISSUE THREAD

**Issue by emil-totev** [mariuz/flamerobin#68]
This is on Windows.
When you double-click an object in the tree (or select 'Properties' from the context menu), the object's properties are displayed on a new tab in the properties window. However if that window has been shown and then minimized, it doesn't get restored, so it seems as if the double-click had no effect. (Actually something flashes briefly on the screen, but that's all).

**Comment by luronumen** [comment]
Hi @emil-totev 

Could you please retest this issue on [FlameRobin 0.9.3.12](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.12) and close it if it is no longer reproducible?

Thanks in advance,
Luciano

**Comment by emil-totev** [comment]
With the latest version (1bd8c1ac) the properties window is shown, but is always maximized. I would expect it to keep the size previously set.
On another note, I still find the versioning scheme quite confusing - the "About" window is showing only the first three groups of numbers (0.9.3 in this case) and a git hash. How are we to know this is 0.9.3.12? And the file version (File properties->details->file version) is 0.9.3.0.
