### ISSUE TITLE
In the "Dependencies" tab for tables, add an pivoted view by column

### ISSUE THREAD

**Issue by arvanus** [mariuz/flamerobin#69]
Today there is 2 views: 

![image](https://user-images.githubusercontent.com/8182958/90804400-8e8f3600-e2f0-11ea-8dd3-c839046f65f6.png)

| TABLE depends on...  | Fields |
|--------|------------|
| TABLE NNNNN | Field1,Field2,Field3... |
| PROCEDURE KKKK | Field2,Field4... |

| Objects that depend on | Fields |
| ------------- | ------------- |
| TABLE YYYY| Field3,Field4,Field5... |
| PROCEDURE GGGG| Field7,Field8... |

My suggestion is to add another, with the same information, but grouped by fields like this:
| Fields| Objects depends on...   |
|--------|------------|
| Field1| TABLE NNNNN, TABLE YYYY, TABLE TTTT, PROCEDURE KKKK, TRIGGER RRRR...  |
| Field4 | PROCEDURE KKKK.... |

Something similar to IBExpert:
![image](https://user-images.githubusercontent.com/8182958/90804216-453ee680-e2f0-11ea-8933-4d59089c0607.png)

What do you think?

**Comment by luronumen** [comment]
Hi @arvanus 

Are you suggesting listing the dependencies by table columns instead of database objects?

**Comment by arvanus** [comment]
Yes, it could help when you are planning to change an specific column, or looking for some bugs

**Comment by luronumen** [comment]
I agree with you.
Would it be possible to implement this feature in this way (one dependency per line)?

![TableDep](https://user-images.githubusercontent.com/8019466/90835225-67e9f300-e322-11ea-933c-9034868a7bb9.png)

**Comment by arvanus** [comment]
yeah
The problem is to understand how it's done the get the data
This template feature is awesome, but strange too 😄

**Comment by mariuz** [comment]
@arvanus please create new branch with this feature and then it can be merged to master after testing
