### ISSUE TITLE
How to compile to windows?

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [mariuz/flamerobin#7]
Hello, could someone help me to compile to windows?
Thanks in advance.

**Comment by moyzer** [comment]
+1
Yes you are right  !!!
Mariuz can give a **Setup for windows 32/64**  
We really need it.

**Comment by tuksik** [comment]
You can check
[Flamerobin Building instructions for Windows 10 (Visual Studion 2015)](http://flamerobin.blogspot.gr/2015/11/flamerobin-building-instructions-for.html)

**Comment by mariuz** [comment]
I have upgraded the instructions above to use the VC14 also solutions are now using wxwidgets 3.1

**Comment by mariuz** [comment]
@moyzer 
Could you try this build for Windows 32 (Debug mode)

https://sourceforge.net/projects/flamerobin/files/flamerobin-snapshots/0.9.x/flamerobin-0.9.3.c75f861-setup-debug.exe/download

**Comment by mariuz** [comment]
you might need Visual C++ Redistributable for Visual Studio 2015

https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by moyzer** [comment]
Thank you Marius.
I will chek it and come back.
