### ISSUE TITLE
Add support for DDL triggers

### ISSUE THREAD

**Issue by arvanus** [mariuz/flamerobin#70]
Relates to #48 
Add support for DDL triggers, example:
```
SET TERM ^ ;
create trigger trig_ddl_sp before CREATE PROCEDURE
as
begin
end!
SET TERM ; ^
```
Get extracted as
```
SET TERM ^ ;
CREATE OR ALTER TRIGGER TRIG_DDL_SP ACTIVE
AFTER  OR UPDATE POSITION 0
as
begin
end^
SET TERM ; ^

```

Needs to get RDB$TRIGGERS.RDB$TRIGGER_TYPE complete documentation to fix
 https://github.com/mariuz/flamerobin/blob/01ff896ef13b0c4c254082c899d3f22cef9b47d1/src/metadata/trigger.cpp#L45
And:
https://github.com/mariuz/flamerobin/blob/01ff896ef13b0c4c254082c899d3f22cef9b47d1/src/metadata/trigger.cpp#L207
And who knows where else 👍

**Comment by luronumen** [comment]
Hi @arvanus,
 
Is this issue still reproducible in [0.9.3.8 Snapshot](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.8) version?

**Comment by arvanus** [comment]
It's working now
