### ISSUE TITLE
Duplicating trigger source

### ISSUE THREAD

**Issue by arvanus** [mariuz/flamerobin#73]
@Jdochoa always when I recompile an trigger, its source code gets duplicated in the trigger part 
This occurs only in your code, can you take an look?
![image](https://user-images.githubusercontent.com/8182958/90957475-23667080-e464-11ea-92a3-877106a8447a.png)

Steps to reproduce: 
Open any (table) trigger
Click on Source "Edit"
Run code
Check trigger Summary again, it's already wrong
Just to check, if you click "Edit" it's wrong
Thanks

**Comment by Jdochoa** [comment]
> 
> 
> @Jdochoa another bug:
> ![image](https://user-images.githubusercontent.com/8182958/90958163-f1a3d880-e468-11ea-86ea-dbfaf71448d8.png)
> No database triggers found at database triggers property

@arvanus  I planning about remove this.
What do you think?

**Comment by Jdochoa** [comment]
> 
> 
> @Jdochoa always when I recompile an trigger, its source code gets duplicated in the trigger part
> This occurs only in your code, can you take an look?
> ![image](https://user-images.githubusercontent.com/8182958/90957475-23667080-e464-11ea-92a3-877106a8447a.png)
> 
> Steps to reproduce:
> Open any (table) trigger
> Click on Source "Edit"
> Run code
> Check trigger Summary again, it's already wrong
> Just to check, if you click "Edit" it's wrong
> Thanks

Fixed up

**Comment by arvanus** [comment]
> 
> 
> > @Jdochoa another bug:
> > ![image](https://user-images.githubusercontent.com/8182958/90958163-f1a3d880-e468-11ea-86ea-dbfaf71448d8.png)
> > No database triggers found at database triggers property
> 
> @arvanus I planning about remove this.
> What do you think?

Well I think that for an consistency behavior, it's better to keep it here too. 
Exactly like in the tables where you have an Trigger tab, in your database you have triggers too, so I would consider to be consistent to keep then in this tab too

**Comment by arvanus** [comment]
@Jdochoa I'd ask you, to if possible to focus in one feature at time, this way I can test and publish as soon as possible.
Lets build an chronogram or something like that? This way I can help you too if I know what you are working at, what do you think?

**Comment by luronumen** [comment]
I agree with @arvanus .
Let's first focus on fixing all known bugs and then move on to implementing new features.

**Comment by Jdochoa** [comment]
Hi @luronumen, @arvanus, @mariuz 
I completely agree with you.
What do you think if defined a roadmap and assigned a responsible for each issue?
**The features in i worked are:**
- Database:
  - SQL Security
  - Linger
- Procedures:
  - Hide  procedures from  packages.
  - UDR functionality.
  - SQL Security
- Functions:
  - Hide functions from packages.
  - UDR functionality.
  - Separate UDF.
  - PSQL Functions.
  - SQL Security
- Domains:
  - separate sysdomain.
- Triggers:
  - Separate DDL Triggers.
  - Separate DB Triggers.
   - SQL Security
- Tables:
   - Separatte GTT.
   - SQL Security
- Packages:
  - Basic functionality.
  - SQL Security

**I wi'll worker in:**
- Database:
  - Replication.
- Functions:
  - Finish functionality.
- Packages:
  - Finish functionality.
  - Agregate syspackages.
- Index.
  - Add index node.
- Domains:
  - Upgrade functionality.
- Tables:
  - Agregate Identity columns.
  - Complete functionality GTT.
  - Replication.
- FB 4 DataTypes


Doy you have a list from bugs?

**Comment by Jdochoa** [comment]
> 
> 
> @Jdochoa another bug:
> ![image](https://user-images.githubusercontent.com/8182958/90958163-f1a3d880-e468-11ea-86ea-dbfaf71448d8.png)
> No database triggers found at database triggers property
Fix it.

**Comment by luronumen** [comment]
Hi @Jdochoa 

Excellent roadmap that you created. I find it very interesting if we can continue with this planning.
Please notify me when the bugs / features you are working on are ready for testing. I can help you with this activity before a new version is released.

Thank you very much for your dedication to this project as one of the best Firebird Admin in the world.

Best Regards,
Luciano

**Comment by Jdochoa** [comment]
Hi @arvanus 
Can you give me feedback on this or close it?

Thanks 
./jo

**Comment by arvanus** [comment]
Done, just lets organize what is pending for the next stable release? (not snapshot) 0.9.4

**Comment by Jdochoa** [comment]
> 
> 
> Done, just lets organize what is pending for the next stable release? (not snapshot) 0.9.4

Please view Roadmap #216

:/jo
