### ISSUE TITLE
New branchs for testings

### ISSUE THREAD

**Issue by arvanus** [mariuz/flamerobin#74]
Hi everybody
@mariuz what do you think about making an new branch specific for testings and new features?
For example #69 and the new resources for Fb3?
It would help keeping a more stable for the majority of users, and would make easier the deploy of testing code
For now, just an "Testing" branch would be OK, and maybe the new features for FB3 would be a part of

**Comment by mariuz** [comment]
yes you can create a new branch for testing new features
