### ISSUE TITLE
Alter View instead of Drop/create

### ISSUE THREAD

**Issue by pgiacomo69** [mariuz/flamerobin#76]
Firebird 2.5 and up support ALTER VIEW, it would be possible to change behavior from current "rebuiild" to a simpler "alter view"?
Alternatively, current menu command can be renamed to "Rebuild View" and a  new "Alter view" command can be added.

**Comment by luronumen** [comment]
Hi @pgiacomo69 ,
 
Is this issue still reproducible in [0.9.3.8 Snapshot](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.8) version?

**Comment by pgiacomo69** [comment]
Ok!
