### ISSUE TITLE
Some bugs in the new pivoted view by column table Dependencies tab

### ISSUE THREAD

**Issue by luronumen** [mariuz/flamerobin#77]
1 - The **field order** must be the same as the **field order in the table**:
![Untitled](https://user-images.githubusercontent.com/8019466/91166325-93653880-e6a8-11ea-8092-b8b250c96374.png)

2 - For some unknown reason, some tables appeared after the procedures:
![Untitled2](https://user-images.githubusercontent.com/8019466/91166445-c4456d80-e6a8-11ea-81d0-c5161487769a.png)

3- Replace **Objects related to USERS Fields** with **Objects that depend on USERS field**
4- The table that the field belongs to (e.g.: **Users**) should not be listed as it depends, but only the other objects in the database:
![Untitled3](https://user-images.githubusercontent.com/8019466/91167214-f0152300-e6a9-11ea-8cac-2316e1e49549.png)

**Comment by arvanus** [comment]
Hi @luronumen, thanks for your feedback ASAP!
I'l take a look about your suggestions and fix where possible! 

About item 4:

> 4- The table that the field belongs to (e.g.: Users) should not be listed as it depends, but only the other objects in the database:

If you take a look at previous dependency tables I guess that the table USERS is listed there too (am I right?) I just used that functionality pivoted. What we could do, is increase the info like in IBExpert (see differences bellow)
![image](https://user-images.githubusercontent.com/8182958/91341895-a105e580-e7b0-11ea-8d95-7c7ea8b60070.png)
![image](https://user-images.githubusercontent.com/8182958/91341929-ae22d480-e7b0-11ea-9d4f-e2a9e18a1abe.png)
![image](https://user-images.githubusercontent.com/8182958/91341952-b713a600-e7b0-11ea-81fb-4ae6009dbb8a.png)

Flamerobin ignores the FK and just show the origin table, basically it's an old bug that you found in this new feature  😄 

PS: ID_FK uses an FK table, and doesn't show in FR
![image](https://user-images.githubusercontent.com/8182958/91342361-4de06280-e7b1-11ea-81f6-95cf3fdd6464.png)

**Comment by luronumen** [comment]
I liked your suggestion for item 4, @arvanus! :)

**Comment by arvanus** [comment]
The number 1 will be pretty hard do accomplish, because basically this selects don't offer the position info, I'd change a bit to do it
I'm working on number 2 right now, apparently this occurred because that table have FK and are used by other tables too
Before sorting:
![image](https://user-images.githubusercontent.com/8182958/91647697-fdc50280-ea33-11ea-814d-6e997e012608.png)
After sorting:
![image](https://user-images.githubusercontent.com/8182958/91647711-3e248080-ea34-11ea-826c-42ecd5da288e.png)
Number 3: changed 😄

**Comment by luronumen** [comment]
The item 2 looks pretty good @arvanus! Good job!

I would like to suggest one more adjustment:
Instead of just being **Fields** in the first table header, what do you think if we put **< Table name > field** like this:
- **USERS field**
- **Objects that depend on USERS field**

**Comment by arvanus** [comment]
Updating:
![image](https://user-images.githubusercontent.com/8182958/91666907-218d5480-ead7-11ea-8137-0134cf240cc7.png)
![image](https://user-images.githubusercontent.com/8182958/91666913-30740700-ead7-11ea-81d8-e3d4d33fafb1.png)
It's a silly thing, but I couldn't simply put "TABLE NNN FOREIGN KEY (FK_NNN_LLL)", so I showed like this: TABLE NNN (FK_NNN_LLL) because every other object has its own kind, but FK was unknown 😢

**Comment by luronumen** [comment]
Hi @arvanus 

Is it possible to do like that:

**TABLE AAA (FOREIGN KEY: BBB)** or **TABLE AAA (CONSTRAINT: BBB)** ?

**Comment by arvanus** [comment]
@luronumen take a look how is it now!

**Comment by luronumen** [comment]
Hi @arvanus,

There are some fields in the table that still show that it depends on the current table:

![01](https://user-images.githubusercontent.com/8019466/93669927-a2ec5d00-fa6d-11ea-8283-707e7d785079.png)

But in the same table (e.g.: Users) there are other fields that do not show that it depends on the current table:

![02](https://user-images.githubusercontent.com/8019466/93669939-bc8da480-fa6d-11ea-9ca1-91ad931bb9d8.png)

How is this possible?

**Comment by arvanus** [comment]
Can you provide me a simple DDL that the dependency appears wrongly?
Thanks

**Comment by luronumen** [comment]
Hi @arvanus 

This issue happens with table fields used in COMPUTED BY (e.g.: UID, LAST_NAME and FIRST_NAME):

CREATE TABLE USERS (UID VARCHAR(32) CHARACTER SET WIN1252 NOT NULL COLLATE WIN_PTBR,
        LAST_NAME VARCHAR(32) CHARACTER SET WIN1252 NOT NULL COLLATE WIN_PTBR,
        FIRST_NAME VARCHAR(32) CHARACTER SET WIN1252 NOT NULL COLLATE WIN_PTBR,
        AUTHENTICATION VARCHAR(32) CHARACTER SET WIN1252 COLLATE WIN_PTBR,
        EMAIL VARCHAR(32) CHARACTER SET WIN1252 COLLATE WIN_PTBR,
        FULL_NAME VARCHAR(100) COMPUTED BY (NULL),
CONSTRAINT USERS_PK PRIMARY KEY (UID),
CONSTRAINT USERS_UK_1 UNIQUE (AUTHENTICATION),
CONSTRAINT USERS_UK_2 UNIQUE (EMAIL));

ALTER TABLE USERS
        ALTER FULL_NAME TYPE VARCHAR(100) COMPUTED BY (CAST((FIRST_NAME || ' ' || LAST_NAME || ' (' || UID || ')') AS VARCHAR(100) CHARACTER SET WIN1252) COLLATE WIN_PTBR);

I don't know if this should be considered a issue. How does this scenario work at IBExpert?

Best Regards,
Luciano

**Comment by luronumen** [comment]
Retest result on [FlameRobin 0.9.3.8 Snapshot](https://github.com/mariuz/flamerobin/releases/tag/0.9.3.8): **Passed!**

Thank you very much for the fix!
