### ISSUE TITLE
extract metadata and criar database import metadata

### ISSUE THREAD

**Issue by danielquahato** [mariuz/flamerobin#84]
possibility to extract metadata and create a new database with the imported metata

**Comment by arvanus** [comment]
You can extract the metadata by right click the database, then properties and then "DDL", create a new database and import the extracted DDL
I don't know if it's what you mean

Also, you can create a database backup with metadata only:
![image](https://user-images.githubusercontent.com/8182958/92845011-db7c9e80-f3bc-11ea-8b26-35d9ba8f5383.png)
After that restore like a normal backup
