### ISSUE TITLE
Crash in MSVCP140D.dll on typing period

### ISSUE THREAD

**Issue by WaveyMaple** [mariuz/flamerobin#9]
I am running FlameRobin 0.9.3 (git hash c75f861), on a machine that also has VS2013 (no later version). When I open (Database menu | Execute SQL statements) and type the following SQL, the moment I hit the final period after NEW the program crashes (screen cap attached).

It would seem from the crash message that this version of FlameRobin is built against a debug DLL. Note that repeating the steps above in FlameRobin 0.9.3.2219.

CREATE TABLE VUSER
(
  ID integer NOT NULL,
  RDBUSER varchar(31) COLLATE UNICODE NOT NULL,
  GUID char(16) NOT NULL,
  STATUS integer NOT NULL,
  EMAIL varchar(255) COLLATE UNICODE,
  DOMAINUSER varchar(255) COLLATE UNICODE,
  DOMAINNAME varchar(255) COLLATE UNICODE,
  NOTES varchar(255) COLLATE UNICODE,
  CREATEDBY integer NOT NULL,
  CREATEDATE timestamp NOT NULL,
  MODBY integer NOT NULL,
  MODDATE timestamp NOT NULL,
  CONSTRAINT INTEG_25 PRIMARY KEY (ID)
);
CREATE INDEX IDXPATIENTDATABASEID ON PATIENT (DATABASEID);

CREATE GENERATOR VUSERGEN;

CREATE TRIGGER VUSERTRIG FOR VUSER
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
	IF (NEW.

![screenshot - 12_14_2016 4_46_29 pm](https://cloud.githubusercontent.com/assets/4533682/21284669/4a47af0e-c3d7-11e6-8343-98f08210e976.png)

**Comment by mariuz** [comment]
please try the new snasphot installer , is built with no debug runtime

**Comment by WaveyMaple** [comment]
Sorry for the dumb question here - I am new to FlameRobin and GitHub. Where do I get the new snapshot installer? When I look here:
http://www.flamerobin.org/
it is showing the same version  0.9.3 (git hash c75f861) that I was using that crashes.

**Comment by arvanus** [comment]
Hi, please test the latest snapshot available and let me know if it's working
https://github.com/mariuz/flamerobin/releases/tag/0.9.3.2

**Comment by arvanus** [comment]
![image](https://user-images.githubusercontent.com/8182958/90293327-38d30d80-de5a-11ea-9793-f20ad4fb804a.png)
I'll close the issue, anything reopen later, OK?
